/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "AccessStratumReleaseIndicator.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_AccessStratumReleaseIndicator_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AccessStratumReleaseIndicator_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_AccessStratumReleaseIndicator_value2enum_1[] = {
	{ 0,	5,	"rel-4" },
	{ 1,	5,	"rel-5" },
	{ 2,	5,	"rel-6" },
	{ 3,	5,	"rel-7" },
	{ 4,	7,	"spare12" },
	{ 5,	7,	"spare11" },
	{ 6,	7,	"spare10" },
	{ 7,	6,	"spare9" },
	{ 8,	6,	"spare8" },
	{ 9,	6,	"spare7" },
	{ 10,	6,	"spare6" },
	{ 11,	6,	"spare5" },
	{ 12,	6,	"spare4" },
	{ 13,	6,	"spare3" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static const unsigned int asn_MAP_AccessStratumReleaseIndicator_enum2value_1[] = {
	0,	/* rel-4(0) */
	1,	/* rel-5(1) */
	2,	/* rel-6(2) */
	3,	/* rel-7(3) */
	15,	/* spare1(15) */
	6,	/* spare10(6) */
	5,	/* spare11(5) */
	4,	/* spare12(4) */
	14,	/* spare2(14) */
	13,	/* spare3(13) */
	12,	/* spare4(12) */
	11,	/* spare5(11) */
	10,	/* spare6(10) */
	9,	/* spare7(9) */
	8,	/* spare8(8) */
	7	/* spare9(7) */
};
const asn_INTEGER_specifics_t asn_SPC_AccessStratumReleaseIndicator_specs_1 = {
	asn_MAP_AccessStratumReleaseIndicator_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_AccessStratumReleaseIndicator_enum2value_1,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_AccessStratumReleaseIndicator_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AccessStratumReleaseIndicator = {
	"AccessStratumReleaseIndicator",
	"AccessStratumReleaseIndicator",
	&asn_OP_NativeEnumerated,
	asn_DEF_AccessStratumReleaseIndicator_tags_1,
	sizeof(asn_DEF_AccessStratumReleaseIndicator_tags_1)
		/sizeof(asn_DEF_AccessStratumReleaseIndicator_tags_1[0]), /* 1 */
	asn_DEF_AccessStratumReleaseIndicator_tags_1,	/* Same as above */
	sizeof(asn_DEF_AccessStratumReleaseIndicator_tags_1)
		/sizeof(asn_DEF_AccessStratumReleaseIndicator_tags_1[0]), /* 1 */
	{ &asn_OER_type_AccessStratumReleaseIndicator_constr_1, &asn_PER_type_AccessStratumReleaseIndicator_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_AccessStratumReleaseIndicator_specs_1	/* Additional specs */
};

