/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "ActiveSetUpdate.h"

static asn_oer_constraints_t asn_OER_type_criticalExtensions_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ActiveSetUpdate_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ActiveSetUpdate_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_12 = {
	sizeof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_12 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_12,
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions, activeSetUpdate_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActiveSetUpdate_v690ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_10[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activeSetUpdate-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_10 = {
	sizeof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions),
	offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_10 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v690NonCriticalExtensions_tags_10,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v690NonCriticalExtensions_10,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtensions_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions, activeSetUpdate_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActiveSetUpdate_v590ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v590NonCriticalExtensions_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activeSetUpdate-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtensions_specs_8 = {
	sizeof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions),
	offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions, _asn_ctx),
	asn_MAP_v590NonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtensions_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtensions_8 = {
	"v590NonCriticalExtensions",
	"v590NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v590NonCriticalExtensions_tags_8,
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v590NonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions, activeSetUpdate_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActiveSetUpdate_v4b0ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions, v590NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v590NonCriticalExtensions"
		},
};
static const int asn_MAP_v4b0NonCriticalExtensions_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activeSetUpdate-v4b0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_6 = {
	sizeof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions),
	offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_6 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v4b0NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v4b0NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_laterNonCriticalExtensions_4[] = {
	{ ATF_POINTER, 2, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions, activeSetUpdate_r3_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-r3-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v4b0NonCriticalExtensions"
		},
};
static const int asn_MAP_laterNonCriticalExtensions_oms_4[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_laterNonCriticalExtensions_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_laterNonCriticalExtensions_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activeSetUpdate-r3-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v4b0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_laterNonCriticalExtensions_specs_4 = {
	sizeof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions),
	offsetof(struct ActiveSetUpdate__r3__laterNonCriticalExtensions, _asn_ctx),
	asn_MAP_laterNonCriticalExtensions_tag2el_4,
	2,	/* Count of tags in the map */
	asn_MAP_laterNonCriticalExtensions_oms_4,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laterNonCriticalExtensions_4 = {
	"laterNonCriticalExtensions",
	"laterNonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_laterNonCriticalExtensions_tags_4,
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_4[0]) - 1, /* 1 */
	asn_DEF_laterNonCriticalExtensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_laterNonCriticalExtensions_4,
	2,	/* Elements count */
	&asn_SPC_laterNonCriticalExtensions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r3_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__r3, activeSetUpdate_r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActiveSetUpdate_r3_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-r3"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveSetUpdate__r3, laterNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_laterNonCriticalExtensions_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laterNonCriticalExtensions"
		},
};
static const int asn_MAP_r3_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r3_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r3_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activeSetUpdate-r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* laterNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r3_specs_2 = {
	sizeof(struct ActiveSetUpdate__r3),
	offsetof(struct ActiveSetUpdate__r3, _asn_ctx),
	asn_MAP_r3_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_r3_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r3_2 = {
	"r3",
	"r3",
	&asn_OP_SEQUENCE,
	asn_DEF_r3_tags_2,
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]) - 1, /* 1 */
	asn_DEF_r3_tags_2,	/* Same as above */
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r3_2,
	2,	/* Elements count */
	&asn_SPC_r3_specs_2	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_19 = {
	sizeof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6__nonCriticalExtensions),
	offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_19 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_19,
	sizeof(asn_DEF_nonCriticalExtensions_tags_19)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_19[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_19,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_19)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_19[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r6_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6, activeSetUpdate_r6),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActiveSetUpdate_r6_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-r6"
		},
	{ ATF_POINTER, 2, offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6, activeSetUpdate_r6_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"activeSetUpdate-r6-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r6_oms_16[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_r6_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r6_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activeSetUpdate-r6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* activeSetUpdate-r6-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r6_specs_16 = {
	sizeof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6),
	offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__r6, _asn_ctx),
	asn_MAP_r6_tag2el_16,
	3,	/* Count of tags in the map */
	asn_MAP_r6_oms_16,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r6_16 = {
	"r6",
	"r6",
	&asn_OP_SEQUENCE,
	asn_DEF_r6_tags_16,
	sizeof(asn_DEF_r6_tags_16)
		/sizeof(asn_DEF_r6_tags_16[0]) - 1, /* 1 */
	asn_DEF_r6_tags_16,	/* Same as above */
	sizeof(asn_DEF_r6_tags_16)
		/sizeof(asn_DEF_r6_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r6_16,
	3,	/* Elements count */
	&asn_SPC_r6_specs_16	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_criticalExtensions_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensions_specs_20 = {
	sizeof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__criticalExtensions),
	offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions__criticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_20 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_criticalExtensions_tags_20,
	sizeof(asn_DEF_criticalExtensions_tags_20)
		/sizeof(asn_DEF_criticalExtensions_tags_20[0]) - 1, /* 1 */
	asn_DEF_criticalExtensions_tags_20,	/* Same as above */
	sizeof(asn_DEF_criticalExtensions_tags_20)
		/sizeof(asn_DEF_criticalExtensions_tags_20[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_criticalExtensions_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_15[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions, choice.r6),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r6_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_criticalExtensions_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_15 = {
	sizeof(struct ActiveSetUpdate__later_than_r3__criticalExtensions),
	offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions, _asn_ctx),
	offsetof(struct ActiveSetUpdate__later_than_r3__criticalExtensions, present),
	sizeof(((struct ActiveSetUpdate__later_than_r3__criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_15,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_15 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_criticalExtensions_constr_15, &asn_PER_type_criticalExtensions_constr_15, CHOICE_constraint },
	asn_MBR_criticalExtensions_15,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_later_than_r3_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__later_than_r3, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rrc-TransactionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate__later_than_r3, criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const ber_tlv_tag_t asn_DEF_later_than_r3_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_later_than_r3_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrc-TransactionIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_later_than_r3_specs_13 = {
	sizeof(struct ActiveSetUpdate__later_than_r3),
	offsetof(struct ActiveSetUpdate__later_than_r3, _asn_ctx),
	asn_MAP_later_than_r3_tag2el_13,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_later_than_r3_13 = {
	"later-than-r3",
	"later-than-r3",
	&asn_OP_SEQUENCE,
	asn_DEF_later_than_r3_tags_13,
	sizeof(asn_DEF_later_than_r3_tags_13)
		/sizeof(asn_DEF_later_than_r3_tags_13[0]) - 1, /* 1 */
	asn_DEF_later_than_r3_tags_13,	/* Same as above */
	sizeof(asn_DEF_later_than_r3_tags_13)
		/sizeof(asn_DEF_later_than_r3_tags_13[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_later_than_r3_13,
	2,	/* Elements count */
	&asn_SPC_later_than_r3_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ActiveSetUpdate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate, choice.r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r3_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveSetUpdate, choice.later_than_r3),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_later_than_r3_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"later-than-r3"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ActiveSetUpdate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* later-than-r3 */
};
asn_CHOICE_specifics_t asn_SPC_ActiveSetUpdate_specs_1 = {
	sizeof(struct ActiveSetUpdate),
	offsetof(struct ActiveSetUpdate, _asn_ctx),
	offsetof(struct ActiveSetUpdate, present),
	sizeof(((struct ActiveSetUpdate *)0)->present),
	asn_MAP_ActiveSetUpdate_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ActiveSetUpdate = {
	"ActiveSetUpdate",
	"ActiveSetUpdate",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ActiveSetUpdate_constr_1, &asn_PER_type_ActiveSetUpdate_constr_1, CHOICE_constraint },
	asn_MBR_ActiveSetUpdate_1,
	2,	/* Elements count */
	&asn_SPC_ActiveSetUpdate_specs_1	/* Additional specs */
};

