/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "ChipRateCapability-r7.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ChipRateCapability_r7_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ChipRateCapability_r7_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ChipRateCapability_r7_value2enum_1[] = {
	{ 0,	8,	"mcps3-84" },
	{ 1,	8,	"mcps7-68" },
	{ 2,	8,	"mcps1-28" }
};
static const unsigned int asn_MAP_ChipRateCapability_r7_enum2value_1[] = {
	2,	/* mcps1-28(2) */
	0,	/* mcps3-84(0) */
	1	/* mcps7-68(1) */
};
const asn_INTEGER_specifics_t asn_SPC_ChipRateCapability_r7_specs_1 = {
	asn_MAP_ChipRateCapability_r7_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ChipRateCapability_r7_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ChipRateCapability_r7_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ChipRateCapability_r7 = {
	"ChipRateCapability-r7",
	"ChipRateCapability-r7",
	&asn_OP_NativeEnumerated,
	asn_DEF_ChipRateCapability_r7_tags_1,
	sizeof(asn_DEF_ChipRateCapability_r7_tags_1)
		/sizeof(asn_DEF_ChipRateCapability_r7_tags_1[0]), /* 1 */
	asn_DEF_ChipRateCapability_r7_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChipRateCapability_r7_tags_1)
		/sizeof(asn_DEF_ChipRateCapability_r7_tags_1[0]), /* 1 */
	{ &asn_OER_type_ChipRateCapability_r7_constr_1, &asn_PER_type_ChipRateCapability_r7_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ChipRateCapability_r7_specs_1	/* Additional specs */
};

