/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_DL_CCTrChTPCList_H_
#define	_DL_CCTrChTPCList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TFCS_Identity;

/* DL-CCTrChTPCList */
typedef struct DL_CCTrChTPCList {
	A_SEQUENCE_OF(struct TFCS_Identity) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_CCTrChTPCList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_CCTrChTPCList;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_CCTrChTPCList_H_ */
#include <asn_internal.h>
