/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_Event3a_H_
#define	_Event3a_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Threshold.h"
#include "W.h"
#include "Hysteresis.h"
#include "TimeToTrigger.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReportingCellStatus;

/* Event3a */
typedef struct Event3a {
	Threshold_t	 thresholdOwnSystem;
	W_t	 w;
	Threshold_t	 thresholdOtherSystem;
	Hysteresis_t	 hysteresis;
	TimeToTrigger_t	 timeToTrigger;
	struct ReportingCellStatus	*reportingCellStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Event3a_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Event3a;
extern asn_SEQUENCE_specifics_t asn_SPC_Event3a_specs_1;
extern asn_TYPE_member_t asn_MBR_Event3a_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _Event3a_H_ */
#include <asn_internal.h>
