/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_Event1b_H_
#define	_Event1b_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TriggeringCondition1.h"
#include "ReportingRange.h"
#include "W.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ForbiddenAffectCellList;

/* Event1b */
typedef struct Event1b {
	TriggeringCondition1_t	 triggeringCondition;
	ReportingRange_t	 reportingRange;
	struct ForbiddenAffectCellList	*forbiddenAffectCellList	/* OPTIONAL */;
	W_t	 w;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Event1b_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Event1b;
extern asn_SEQUENCE_specifics_t asn_SPC_Event1b_specs_1;
extern asn_TYPE_member_t asn_MBR_Event1b_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _Event1b_H_ */
#include <asn_internal.h>
