/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "HandoverToUTRANCommand.h"

static asn_oer_constraints_t asn_OER_type_criticalExtensions_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_criticalExtensions_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_criticalExtensions_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_criticalExtensions_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_HandoverToUTRANCommand_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_HandoverToUTRANCommand_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_4 = {
	sizeof(struct HandoverToUTRANCommand__r3__nonCriticalExtensions),
	offsetof(struct HandoverToUTRANCommand__r3__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_4 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_4,
	sizeof(asn_DEF_nonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_4[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r3_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__r3, handoverToUTRANCommand_r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverToUTRANCommand_r3_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverToUTRANCommand-r3"
		},
	{ ATF_POINTER, 1, offsetof(struct HandoverToUTRANCommand__r3, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r3_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r3_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r3_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* handoverToUTRANCommand-r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r3_specs_2 = {
	sizeof(struct HandoverToUTRANCommand__r3),
	offsetof(struct HandoverToUTRANCommand__r3, _asn_ctx),
	asn_MAP_r3_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_r3_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r3_2 = {
	"r3",
	"r3",
	&asn_OP_SEQUENCE,
	asn_DEF_r3_tags_2,
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]) - 1, /* 1 */
	asn_DEF_r3_tags_2,	/* Same as above */
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r3_2,
	2,	/* Elements count */
	&asn_SPC_r3_specs_2	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_8 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__r4__nonCriticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__r4__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_8 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_8,
	sizeof(asn_DEF_nonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r4_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__r4, handoverToUTRANCommand_r4),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverToUTRANCommand_r4_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverToUTRANCommand-r4"
		},
	{ ATF_POINTER, 1, offsetof(struct HandoverToUTRANCommand__criticalExtensions__r4, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r4_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r4_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r4_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* handoverToUTRANCommand-r4 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r4_specs_6 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__r4),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__r4, _asn_ctx),
	asn_MAP_r4_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_r4_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r4_6 = {
	"r4",
	"r4",
	&asn_OP_SEQUENCE,
	asn_DEF_r4_tags_6,
	sizeof(asn_DEF_r4_tags_6)
		/sizeof(asn_DEF_r4_tags_6[0]) - 1, /* 1 */
	asn_DEF_r4_tags_6,	/* Same as above */
	sizeof(asn_DEF_r4_tags_6)
		/sizeof(asn_DEF_r4_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r4_6,
	2,	/* Elements count */
	&asn_SPC_r4_specs_6	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_12 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__r5__nonCriticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__r5__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_12 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_12,
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_12[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r5_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__r5, handoverToUTRANCommand_r5),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverToUTRANCommand_r5_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverToUTRANCommand-r5"
		},
	{ ATF_POINTER, 1, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__r5, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r5_oms_10[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r5_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r5_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* handoverToUTRANCommand-r5 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r5_specs_10 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__r5),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__r5, _asn_ctx),
	asn_MAP_r5_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_r5_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r5_10 = {
	"r5",
	"r5",
	&asn_OP_SEQUENCE,
	asn_DEF_r5_tags_10,
	sizeof(asn_DEF_r5_tags_10)
		/sizeof(asn_DEF_r5_tags_10[0]) - 1, /* 1 */
	asn_DEF_r5_tags_10,	/* Same as above */
	sizeof(asn_DEF_r5_tags_10)
		/sizeof(asn_DEF_r5_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r5_10,
	2,	/* Elements count */
	&asn_SPC_r5_specs_10	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_16 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__r6__nonCriticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__r6__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_16 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_16,
	sizeof(asn_DEF_nonCriticalExtensions_tags_16)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_16[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_16,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_16)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r6_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__r6, handoverToUTRANCommand_r6),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverToUTRANCommand_r6_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverToUTRANCommand-r6"
		},
	{ ATF_POINTER, 1, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__r6, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r6_oms_14[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r6_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r6_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* handoverToUTRANCommand-r6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r6_specs_14 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__r6),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__r6, _asn_ctx),
	asn_MAP_r6_tag2el_14,
	2,	/* Count of tags in the map */
	asn_MAP_r6_oms_14,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r6_14 = {
	"r6",
	"r6",
	&asn_OP_SEQUENCE,
	asn_DEF_r6_tags_14,
	sizeof(asn_DEF_r6_tags_14)
		/sizeof(asn_DEF_r6_tags_14[0]) - 1, /* 1 */
	asn_DEF_r6_tags_14,	/* Same as above */
	sizeof(asn_DEF_r6_tags_14)
		/sizeof(asn_DEF_r6_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r6_14,
	2,	/* Elements count */
	&asn_SPC_r6_specs_14	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_20 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__nonCriticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_20 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_20,
	sizeof(asn_DEF_nonCriticalExtensions_tags_20)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_20[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_20,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_20)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_20[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r7_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7, handoverToUTRANCommand_r7),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverToUTRANCommand_r7_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverToUTRANCommand-r7"
		},
	{ ATF_POINTER, 1, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r7_oms_18[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r7_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r7_tag2el_18[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* handoverToUTRANCommand-r7 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r7_specs_18 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7, _asn_ctx),
	asn_MAP_r7_tag2el_18,
	2,	/* Count of tags in the map */
	asn_MAP_r7_oms_18,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r7_18 = {
	"r7",
	"r7",
	&asn_OP_SEQUENCE,
	asn_DEF_r7_tags_18,
	sizeof(asn_DEF_r7_tags_18)
		/sizeof(asn_DEF_r7_tags_18[0]) - 1, /* 1 */
	asn_DEF_r7_tags_18,	/* Same as above */
	sizeof(asn_DEF_r7_tags_18)
		/sizeof(asn_DEF_r7_tags_18[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r7_18,
	2,	/* Elements count */
	&asn_SPC_r7_specs_18	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_criticalExtensions_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensions_specs_21 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_21 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_criticalExtensions_tags_21,
	sizeof(asn_DEF_criticalExtensions_tags_21)
		/sizeof(asn_DEF_criticalExtensions_tags_21[0]) - 1, /* 1 */
	asn_DEF_criticalExtensions_tags_21,	/* Same as above */
	sizeof(asn_DEF_criticalExtensions_tags_21)
		/sizeof(asn_DEF_criticalExtensions_tags_21[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_criticalExtensions_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions, choice.r7),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r7_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r7"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_criticalExtensions_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r7 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_17 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions, _asn_ctx),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions, present),
	sizeof(((struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_17,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_17 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_criticalExtensions_constr_17, &asn_PER_type_criticalExtensions_constr_17, CHOICE_constraint },
	asn_MBR_criticalExtensions_17,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions, choice.r6),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r6_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_13 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions, _asn_ctx),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions, present),
	sizeof(((struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions__criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_13,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_13 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_criticalExtensions_constr_13, &asn_PER_type_criticalExtensions_constr_13, CHOICE_constraint },
	asn_MBR_criticalExtensions_13,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions, choice.r5),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r5_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r5 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_9 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions, _asn_ctx),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions, present),
	sizeof(((struct HandoverToUTRANCommand__criticalExtensions__criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_9,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_9 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_criticalExtensions_constr_9, &asn_PER_type_criticalExtensions_constr_9, CHOICE_constraint },
	asn_MBR_criticalExtensions_9,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions, choice.r4),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r4_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand__criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r4 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_5 = {
	sizeof(struct HandoverToUTRANCommand__criticalExtensions),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions, _asn_ctx),
	offsetof(struct HandoverToUTRANCommand__criticalExtensions, present),
	sizeof(((struct HandoverToUTRANCommand__criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_5 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_criticalExtensions_constr_5, &asn_PER_type_criticalExtensions_constr_5, CHOICE_constraint },
	asn_MBR_criticalExtensions_5,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_HandoverToUTRANCommand_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand, choice.r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r3_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HandoverToUTRANCommand, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_HandoverToUTRANCommand_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_HandoverToUTRANCommand_specs_1 = {
	sizeof(struct HandoverToUTRANCommand),
	offsetof(struct HandoverToUTRANCommand, _asn_ctx),
	offsetof(struct HandoverToUTRANCommand, present),
	sizeof(((struct HandoverToUTRANCommand *)0)->present),
	asn_MAP_HandoverToUTRANCommand_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_HandoverToUTRANCommand = {
	"HandoverToUTRANCommand",
	"HandoverToUTRANCommand",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_HandoverToUTRANCommand_constr_1, &asn_PER_type_HandoverToUTRANCommand_constr_1, CHOICE_constraint },
	asn_MBR_HandoverToUTRANCommand_1,
	2,	/* Elements count */
	&asn_SPC_HandoverToUTRANCommand_specs_1	/* Additional specs */
};

