/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_InterFrequencyMeasurement_H_
#define	_InterFrequencyMeasurement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InterFreqCellInfoList.h"
#include "InterFreqReportCriteria.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterFreqMeasQuantity;
struct InterFreqReportingQuantity;
struct MeasurementValidity;
struct UE_AutonomousUpdateMode;

/* InterFrequencyMeasurement */
typedef struct InterFrequencyMeasurement {
	InterFreqCellInfoList_t	 interFreqCellInfoList;
	struct InterFreqMeasQuantity	*interFreqMeasQuantity	/* OPTIONAL */;
	struct InterFreqReportingQuantity	*interFreqReportingQuantity	/* OPTIONAL */;
	struct MeasurementValidity	*measurementValidity	/* OPTIONAL */;
	struct UE_AutonomousUpdateMode	*interFreqSetUpdate	/* OPTIONAL */;
	InterFreqReportCriteria_t	 reportCriteria;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFrequencyMeasurement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFrequencyMeasurement;
extern asn_SEQUENCE_specifics_t asn_SPC_InterFrequencyMeasurement_specs_1;
extern asn_TYPE_member_t asn_MBR_InterFrequencyMeasurement_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _InterFrequencyMeasurement_H_ */
#include <asn_internal.h>
