/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_InterRATHandoverInfo_r3_add_ext_IEs_H_
#define	_InterRATHandoverInfo_r3_add_ext_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InterRATHandoverInfo-v690ext1-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InterRATHandoverInfo-r3-add-ext-IEs */
typedef struct InterRATHandoverInfo_r3_add_ext_IEs {
	InterRATHandoverInfo_v690ext1_IEs_t	 interRATHandoverInfo_v690ext1;
	struct InterRATHandoverInfo_r3_add_ext_IEs__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRATHandoverInfo_r3_add_ext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATHandoverInfo_r3_add_ext_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _InterRATHandoverInfo_r3_add_ext_IEs_H_ */
#include <asn_internal.h>
