/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_IntraFrequencyMeasurement_H_
#define	_IntraFrequencyMeasurement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntraFreqCellInfoList;
struct IntraFreqMeasQuantity;
struct IntraFreqReportingQuantity;
struct MeasurementValidity;
struct IntraFreqReportCriteria;

/* IntraFrequencyMeasurement */
typedef struct IntraFrequencyMeasurement {
	struct IntraFreqCellInfoList	*intraFreqCellInfoList	/* OPTIONAL */;
	struct IntraFreqMeasQuantity	*intraFreqMeasQuantity	/* OPTIONAL */;
	struct IntraFreqReportingQuantity	*intraFreqReportingQuantity	/* OPTIONAL */;
	struct MeasurementValidity	*measurementValidity	/* OPTIONAL */;
	struct IntraFreqReportCriteria	*reportCriteria	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntraFrequencyMeasurement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntraFrequencyMeasurement;
extern asn_SEQUENCE_specifics_t asn_SPC_IntraFrequencyMeasurement_specs_1;
extern asn_TYPE_member_t asn_MBR_IntraFrequencyMeasurement_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _IntraFrequencyMeasurement_H_ */
#include <asn_internal.h>
