/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_IntraFreqCellInfoList_r4_H_
#define	_IntraFreqCellInfoList_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RemovedIntraFreqCellList;
struct NewIntraFreqCellList_r4;
struct CellsForIntraFreqMeasList;

/* IntraFreqCellInfoList-r4 */
typedef struct IntraFreqCellInfoList_r4 {
	struct RemovedIntraFreqCellList	*removedIntraFreqCellList	/* OPTIONAL */;
	struct NewIntraFreqCellList_r4	*newIntraFreqCellList	/* OPTIONAL */;
	struct CellsForIntraFreqMeasList	*cellsForIntraFreqMeasList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntraFreqCellInfoList_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntraFreqCellInfoList_r4;
extern asn_SEQUENCE_specifics_t asn_SPC_IntraFreqCellInfoList_r4_specs_1;
extern asn_TYPE_member_t asn_MBR_IntraFreqCellInfoList_r4_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _IntraFreqCellInfoList_r4_H_ */
#include <asn_internal.h>
