/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_IntraFreqReportingQuantity_H_
#define	_IntraFreqReportingQuantity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellReportingQuantities.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellReportingQuantities;

/* IntraFreqReportingQuantity */
typedef struct IntraFreqReportingQuantity {
	CellReportingQuantities_t	 activeSetReportingQuantities;
	CellReportingQuantities_t	 monitoredSetReportingQuantities;
	struct CellReportingQuantities	*detectedSetReportingQuantities	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntraFreqReportingQuantity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntraFreqReportingQuantity;
extern asn_SEQUENCE_specifics_t asn_SPC_IntraFreqReportingQuantity_specs_1;
extern asn_TYPE_member_t asn_MBR_IntraFreqReportingQuantity_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _IntraFreqReportingQuantity_H_ */
#include <asn_internal.h>
