/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MBMSCommonPTMRBInformation.h"

#include "MBMS-TranspChInfoForEachCCTrCh-r6.h"
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_6 = {
	sizeof(struct MBMSCommonPTMRBInformation__nonCriticalExtensions),
	offsetof(struct MBMSCommonPTMRBInformation__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_6 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_6,
	sizeof(asn_DEF_nonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MBMSCommonPTMRBInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation, mbms_CommonRBInformationList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_CommonRBInformationList_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-CommonRBInformationList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation, mbms_TranspChInfoForEachTrCh),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_TranspChInfoForEachTrCh_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-TranspChInfoForEachTrCh"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation, mbms_TranspChInfoForEachCCTrCh),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_TranspChInfoForEachCCTrCh_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-TranspChInfoForEachCCTrCh"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSCommonPTMRBInformation, mbms_PhyChInformationList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_PhyChInformationList_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-PhyChInformationList"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCommonPTMRBInformation, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_MBMSCommonPTMRBInformation_oms_1[] = { 2, 4 };
static const ber_tlv_tag_t asn_DEF_MBMSCommonPTMRBInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MBMSCommonPTMRBInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbms-CommonRBInformationList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mbms-TranspChInfoForEachTrCh */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mbms-TranspChInfoForEachCCTrCh */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mbms-PhyChInformationList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* nonCriticalExtensions */
};
asn_SEQUENCE_specifics_t asn_SPC_MBMSCommonPTMRBInformation_specs_1 = {
	sizeof(struct MBMSCommonPTMRBInformation),
	offsetof(struct MBMSCommonPTMRBInformation, _asn_ctx),
	asn_MAP_MBMSCommonPTMRBInformation_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_MBMSCommonPTMRBInformation_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MBMSCommonPTMRBInformation = {
	"MBMSCommonPTMRBInformation",
	"MBMSCommonPTMRBInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_MBMSCommonPTMRBInformation_tags_1,
	sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1)
		/sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1[0]), /* 1 */
	asn_DEF_MBMSCommonPTMRBInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1)
		/sizeof(asn_DEF_MBMSCommonPTMRBInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MBMSCommonPTMRBInformation_1,
	5,	/* Elements count */
	&asn_SPC_MBMSCommonPTMRBInformation_specs_1	/* Additional specs */
};

