/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_MBMSModificationRequest_H_
#define	_MBMSModificationRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBMS_ServiceIdentity_r6;
struct RB_InformationReleaseList;

/* MBMSModificationRequest */
typedef struct MBMSModificationRequest {
	struct MBMS_ServiceIdentity_r6	*mbms_PreferredFreqRequest	/* OPTIONAL */;
	struct RB_InformationReleaseList	*rb_InformationReleaseList	/* OPTIONAL */;
	struct MBMSModificationRequest__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMSModificationRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMSModificationRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_MBMSModificationRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_MBMSModificationRequest_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MBMSModificationRequest_H_ */
#include <asn_internal.h>
