/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_MBMSCurrentCellPTMRBInformation_H_
#define	_MBMSCurrentCellPTMRBInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBMS_CurrentCell_SCCPCHList_r6;
struct MBMS_SIBType5_SCCPCHList_r6;

/* MBMSCurrentCellPTMRBInformation */
typedef struct MBMSCurrentCellPTMRBInformation {
	struct MBMS_CurrentCell_SCCPCHList_r6	*mbms_CurrentCell_SCCPCHList	/* OPTIONAL */;
	struct MBMS_SIBType5_SCCPCHList_r6	*mbms_SIBType5_SCCPCHList	/* OPTIONAL */;
	struct MBMSCurrentCellPTMRBInformation__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMSCurrentCellPTMRBInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMSCurrentCellPTMRBInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_MBMSCurrentCellPTMRBInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_MBMSCurrentCellPTMRBInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MBMSCurrentCellPTMRBInformation_H_ */
#include <asn_internal.h>
