/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MBMSGeneralInformation.h"

#include "MBMS-PreferredFrequencyList-r6.h"
#include "MBMS-MSCH-ConfigurationInfo-r6.h"
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_9 = {
	sizeof(struct MBMSGeneralInformation__v7xyNonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct MBMSGeneralInformation__v7xyNonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_9 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_9,
	sizeof(asn_DEF_nonCriticalExtensions_tags_9)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_9[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_9,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_9)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v7xyNonCriticalExtensions_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSGeneralInformation__v7xyNonCriticalExtensions, mbmsGenerAlInformation_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSGeneralInformation_v7xyext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbmsGenerAlInformation-v7xyext"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSGeneralInformation__v7xyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v7xyNonCriticalExtensions_oms_7[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v7xyNonCriticalExtensions_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v7xyNonCriticalExtensions_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbmsGenerAlInformation-v7xyext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v7xyNonCriticalExtensions_specs_7 = {
	sizeof(struct MBMSGeneralInformation__v7xyNonCriticalExtensions),
	offsetof(struct MBMSGeneralInformation__v7xyNonCriticalExtensions, _asn_ctx),
	asn_MAP_v7xyNonCriticalExtensions_tag2el_7,
	2,	/* Count of tags in the map */
	asn_MAP_v7xyNonCriticalExtensions_oms_7,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v7xyNonCriticalExtensions_7 = {
	"v7xyNonCriticalExtensions",
	"v7xyNonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v7xyNonCriticalExtensions_tags_7,
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_7)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_7[0]) - 1, /* 1 */
	asn_DEF_v7xyNonCriticalExtensions_tags_7,	/* Same as above */
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_7)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v7xyNonCriticalExtensions_7,
	2,	/* Elements count */
	&asn_SPC_v7xyNonCriticalExtensions_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MBMSGeneralInformation_1[] = {
	{ ATF_POINTER, 1, offsetof(struct MBMSGeneralInformation, mbms_PreferredFrequencyInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_PreferredFrequencyList_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-PreferredFrequencyInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSGeneralInformation, mbms_TimersAndCounters),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_TimersAndCounters_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-TimersAndCounters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSGeneralInformation, michConfigurationInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_MICHConfigurationInfo_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"michConfigurationInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSGeneralInformation, cellGroupIdentity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_CellGroupIdentity_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellGroupIdentity"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSGeneralInformation, mschDefaultConfigurationInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_MSCH_ConfigurationInfo_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mschDefaultConfigurationInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMSGeneralInformation, v7xyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_v7xyNonCriticalExtensions_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v7xyNonCriticalExtensions"
		},
};
static const int asn_MAP_MBMSGeneralInformation_oms_1[] = { 0, 4 };
static const ber_tlv_tag_t asn_DEF_MBMSGeneralInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MBMSGeneralInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbms-PreferredFrequencyInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mbms-TimersAndCounters */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* michConfigurationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cellGroupIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* mschDefaultConfigurationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* v7xyNonCriticalExtensions */
};
asn_SEQUENCE_specifics_t asn_SPC_MBMSGeneralInformation_specs_1 = {
	sizeof(struct MBMSGeneralInformation),
	offsetof(struct MBMSGeneralInformation, _asn_ctx),
	asn_MAP_MBMSGeneralInformation_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_MBMSGeneralInformation_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MBMSGeneralInformation = {
	"MBMSGeneralInformation",
	"MBMSGeneralInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_MBMSGeneralInformation_tags_1,
	sizeof(asn_DEF_MBMSGeneralInformation_tags_1)
		/sizeof(asn_DEF_MBMSGeneralInformation_tags_1[0]), /* 1 */
	asn_DEF_MBMSGeneralInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMSGeneralInformation_tags_1)
		/sizeof(asn_DEF_MBMSGeneralInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MBMSGeneralInformation_1,
	6,	/* Elements count */
	&asn_SPC_MBMSGeneralInformation_specs_1	/* Additional specs */
};

