/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MBMSCurrentCellPTMRBInformation.h"

#include "MBMS-CurrentCell-SCCPCHList-r6.h"
#include "MBMS-SIBType5-SCCPCHList-r6.h"
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_4 = {
	sizeof(struct MBMSCurrentCellPTMRBInformation__nonCriticalExtensions),
	offsetof(struct MBMSCurrentCellPTMRBInformation__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_4 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_4,
	sizeof(asn_DEF_nonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_4[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MBMSCurrentCellPTMRBInformation_1[] = {
	{ ATF_POINTER, 3, offsetof(struct MBMSCurrentCellPTMRBInformation, mbms_CurrentCell_SCCPCHList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_CurrentCell_SCCPCHList_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-CurrentCell-SCCPCHList"
		},
	{ ATF_POINTER, 2, offsetof(struct MBMSCurrentCellPTMRBInformation, mbms_SIBType5_SCCPCHList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_SIBType5_SCCPCHList_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbms-SIBType5-SCCPCHList"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSCurrentCellPTMRBInformation, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_MBMSCurrentCellPTMRBInformation_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MBMSCurrentCellPTMRBInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbms-CurrentCell-SCCPCHList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mbms-SIBType5-SCCPCHList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtensions */
};
asn_SEQUENCE_specifics_t asn_SPC_MBMSCurrentCellPTMRBInformation_specs_1 = {
	sizeof(struct MBMSCurrentCellPTMRBInformation),
	offsetof(struct MBMSCurrentCellPTMRBInformation, _asn_ctx),
	asn_MAP_MBMSCurrentCellPTMRBInformation_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MBMSCurrentCellPTMRBInformation_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MBMSCurrentCellPTMRBInformation = {
	"MBMSCurrentCellPTMRBInformation",
	"MBMSCurrentCellPTMRBInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1,
	sizeof(asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1)
		/sizeof(asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1[0]), /* 1 */
	asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1)
		/sizeof(asn_DEF_MBMSCurrentCellPTMRBInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MBMSCurrentCellPTMRBInformation_1,
	3,	/* Elements count */
	&asn_SPC_MBMSCurrentCellPTMRBInformation_specs_1	/* Additional specs */
};

