/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_MBMS_PreferredFreqRequest_r6_H_
#define	_MBMS_PreferredFreqRequest_r6_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FrequencyInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MBMS-PreferredFreqRequest-r6 */
typedef struct MBMS_PreferredFreqRequest_r6 {
	FrequencyInfo_t	 preferredFreqRequest;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_PreferredFreqRequest_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_PreferredFreqRequest_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_PreferredFreqRequest_r6_H_ */
#include <asn_internal.h>
