/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MBMS-PFLInfo.h"

/*
 * This type is implemented using FrequencyInfo,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_MBMS_PFLInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_MBMS_PFLInfo = {
	"MBMS-PFLInfo",
	"MBMS-PFLInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_MBMS_PFLInfo_tags_1,
	sizeof(asn_DEF_MBMS_PFLInfo_tags_1)
		/sizeof(asn_DEF_MBMS_PFLInfo_tags_1[0]), /* 1 */
	asn_DEF_MBMS_PFLInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMS_PFLInfo_tags_1)
		/sizeof(asn_DEF_MBMS_PFLInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_FrequencyInfo_1,
	1,	/* Elements count */
	&asn_SPC_FrequencyInfo_specs_1	/* Additional specs */
};

