/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MeasuredResults-v7xyext.h"

static asn_oer_constraints_t asn_OER_type_MeasuredResults_v7xyext_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_MeasuredResults_v7xyext_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_MeasuredResults_v7xyext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasuredResults_v7xyext, choice.ueInternalMeasuredResults),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_InternalMeasuredResults_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueInternalMeasuredResults"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MeasuredResults_v7xyext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ueInternalMeasuredResults */
};
static asn_CHOICE_specifics_t asn_SPC_MeasuredResults_v7xyext_specs_1 = {
	sizeof(struct MeasuredResults_v7xyext),
	offsetof(struct MeasuredResults_v7xyext, _asn_ctx),
	offsetof(struct MeasuredResults_v7xyext, present),
	sizeof(((struct MeasuredResults_v7xyext *)0)->present),
	asn_MAP_MeasuredResults_v7xyext_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MeasuredResults_v7xyext = {
	"MeasuredResults-v7xyext",
	"MeasuredResults-v7xyext",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_MeasuredResults_v7xyext_constr_1, &asn_PER_type_MeasuredResults_v7xyext_constr_1, CHOICE_constraint },
	asn_MBR_MeasuredResults_v7xyext_1,
	1,	/* Elements count */
	&asn_SPC_MeasuredResults_v7xyext_specs_1	/* Additional specs */
};

