/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MeasurementControl-v7xyext-IEs.h"

asn_TYPE_member_t asn_MBR_MeasurementControl_v7xyext_IEs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasurementControl_v7xyext_IEs, ue_Positioning_Measurement_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_Measurement_v7xyext,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Positioning-Measurement-v7xyext"
		},
};
static const ber_tlv_tag_t asn_DEF_MeasurementControl_v7xyext_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasurementControl_v7xyext_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ue-Positioning-Measurement-v7xyext */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasurementControl_v7xyext_IEs_specs_1 = {
	sizeof(struct MeasurementControl_v7xyext_IEs),
	offsetof(struct MeasurementControl_v7xyext_IEs, _asn_ctx),
	asn_MAP_MeasurementControl_v7xyext_IEs_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasurementControl_v7xyext_IEs = {
	"MeasurementControl-v7xyext-IEs",
	"MeasurementControl-v7xyext-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasurementControl_v7xyext_IEs_tags_1,
	sizeof(asn_DEF_MeasurementControl_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_MeasurementControl_v7xyext_IEs_tags_1[0]), /* 1 */
	asn_DEF_MeasurementControl_v7xyext_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasurementControl_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_MeasurementControl_v7xyext_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasurementControl_v7xyext_IEs_1,
	1,	/* Elements count */
	&asn_SPC_MeasurementControl_v7xyext_IEs_specs_1	/* Additional specs */
};

