/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "MeasurementReport-v7xyext-IEs.h"

#include "VelocityEstimate.h"
#include "UE-InternalMeasuredResults-r7.h"
asn_TYPE_member_t asn_MBR_MeasurementReport_v7xyext_IEs_1[] = {
	{ ATF_POINTER, 2, offsetof(struct MeasurementReport_v7xyext_IEs, velocityEstimate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VelocityEstimate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"velocityEstimate"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasurementReport_v7xyext_IEs, ue_InternalMeasuredResults),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_InternalMeasuredResults_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-InternalMeasuredResults"
		},
};
static const int asn_MAP_MeasurementReport_v7xyext_IEs_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_MeasurementReport_v7xyext_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasurementReport_v7xyext_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* velocityEstimate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-InternalMeasuredResults */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasurementReport_v7xyext_IEs_specs_1 = {
	sizeof(struct MeasurementReport_v7xyext_IEs),
	offsetof(struct MeasurementReport_v7xyext_IEs, _asn_ctx),
	asn_MAP_MeasurementReport_v7xyext_IEs_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_MeasurementReport_v7xyext_IEs_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasurementReport_v7xyext_IEs = {
	"MeasurementReport-v7xyext-IEs",
	"MeasurementReport-v7xyext-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasurementReport_v7xyext_IEs_tags_1,
	sizeof(asn_DEF_MeasurementReport_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_MeasurementReport_v7xyext_IEs_tags_1[0]), /* 1 */
	asn_DEF_MeasurementReport_v7xyext_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasurementReport_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_MeasurementReport_v7xyext_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasurementReport_v7xyext_IEs_1,
	2,	/* Elements count */
	&asn_SPC_MeasurementReport_v7xyext_IEs_specs_1	/* Additional specs */
};

