/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_PCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_SHCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_SHCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_FACH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_MCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_MSCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverToUTRANCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_InterRATHandoverInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_InterRATHandoverInfo_r3_add_ext_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCConnectionSetupComplete_r3_add_ext_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UECapabilityInformation_r3_add_ext_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_CapabilityContainer_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_RadioAccessCapabilityInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_PhysChCapabilityFDD_r6;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_CCTrChTPCList;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasuredResults_v7xyext;
extern struct asn_TYPE_descriptor_s asn_DEF_MasterInformationBlock;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType1;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType2;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType3;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType4;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType5bis;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType6;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType7;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType8;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType9;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType10;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType11;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType12;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType13;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType13_1;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType13_2;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType13_3;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType13_4;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType14;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType15;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType15_1;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType15_2;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType15_3;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType15_4;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType15_5;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType16;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType17;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoType18;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoTypeSB1;
extern struct asn_TYPE_descriptor_s asn_DEF_SysInfoTypeSB2;
extern struct asn_TYPE_descriptor_s asn_DEF_MBMS_PreferredFreqRequest_r6;
extern struct asn_TYPE_descriptor_s asn_DEF_ToTargetRNC_Container;
extern struct asn_TYPE_descriptor_s asn_DEF_TargetRNC_ToSourceRNC_Container;
extern struct asn_TYPE_descriptor_s asn_DEF_SRNC_RelocationInfo_v3h0ext_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_RadioAccessCapability_r7;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module Class-definitions in rrcstr.asn1 */
	&asn_DEF_DL_DCCH_Message,	
	&asn_DEF_UL_DCCH_Message,	
	&asn_DEF_DL_CCCH_Message,	
	&asn_DEF_UL_CCCH_Message,	
	&asn_DEF_PCCH_Message,	
	&asn_DEF_DL_SHCCH_Message,	
	&asn_DEF_UL_SHCCH_Message,	
	&asn_DEF_BCCH_FACH_Message,	
	&asn_DEF_BCCH_BCH_Message,	
	&asn_DEF_MCCH_Message,	
	&asn_DEF_MSCH_Message,	
	/* From module PDU-definitions in rrcstr.asn1 */
	&asn_DEF_HandoverToUTRANCommand,	
	&asn_DEF_InterRATHandoverInfo,	
	&asn_DEF_InterRATHandoverInfo_r3_add_ext_IEs,	
	&asn_DEF_RRCConnectionSetupComplete_r3_add_ext_IEs,	
	&asn_DEF_UECapabilityInformation_r3_add_ext_IEs,	
	/* From module InformationElements in rrcstr.asn1 */
	&asn_DEF_UE_CapabilityContainer_IEs,	
	&asn_DEF_UE_RadioAccessCapabilityInfo,	
	&asn_DEF_UL_PhysChCapabilityFDD_r6,	
	&asn_DEF_DL_CCTrChTPCList,	
	&asn_DEF_MeasuredResults_v7xyext,	
	&asn_DEF_MasterInformationBlock,	
	&asn_DEF_SysInfoType1,	
	&asn_DEF_SysInfoType2,	
	&asn_DEF_SysInfoType3,	
	&asn_DEF_SysInfoType4,	
	&asn_DEF_SysInfoType5bis,	
	&asn_DEF_SysInfoType6,	
	&asn_DEF_SysInfoType7,	
	&asn_DEF_SysInfoType8,	
	&asn_DEF_SysInfoType9,	
	&asn_DEF_SysInfoType10,	
	&asn_DEF_SysInfoType11,	
	&asn_DEF_SysInfoType12,	
	&asn_DEF_SysInfoType13,	
	&asn_DEF_SysInfoType13_1,	
	&asn_DEF_SysInfoType13_2,	
	&asn_DEF_SysInfoType13_3,	
	&asn_DEF_SysInfoType13_4,	
	&asn_DEF_SysInfoType14,	
	&asn_DEF_SysInfoType15,	
	&asn_DEF_SysInfoType15_1,	
	&asn_DEF_SysInfoType15_2,	
	&asn_DEF_SysInfoType15_3,	
	&asn_DEF_SysInfoType15_4,	
	&asn_DEF_SysInfoType15_5,	
	&asn_DEF_SysInfoType16,	
	&asn_DEF_SysInfoType17,	
	&asn_DEF_SysInfoType18,	
	&asn_DEF_SysInfoTypeSB1,	
	&asn_DEF_SysInfoTypeSB2,	
	&asn_DEF_MBMS_PreferredFreqRequest_r6,	
	/* From module Internode-definitions in rrcstr.asn1 */
	&asn_DEF_ToTargetRNC_Container,	
	&asn_DEF_TargetRNC_ToSourceRNC_Container,	
	&asn_DEF_SRNC_RelocationInfo_v3h0ext_IEs,	
	&asn_DEF_UE_RadioAccessCapability_r7,	
	0
};

