/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_PeriodicalWithReportingCellStatus_H_
#define	_PeriodicalWithReportingCellStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PeriodicalReportingCriteria.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReportingCellStatus;

/* PeriodicalWithReportingCellStatus */
typedef struct PeriodicalWithReportingCellStatus {
	PeriodicalReportingCriteria_t	 periodicalReportingCriteria;
	struct ReportingCellStatus	*reportingCellStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PeriodicalWithReportingCellStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PeriodicalWithReportingCellStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_PeriodicalWithReportingCellStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_PeriodicalWithReportingCellStatus_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PeriodicalWithReportingCellStatus_H_ */
#include <asn_internal.h>
