/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_RF_CapabilityComp_r7_H_
#define	_RF_CapabilityComp_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "RF-CapabBandListFDDComp.h"
#include <constr_CHOICE.h>
#include "RadioFrequencyBandTDDList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RF_CapabilityComp_r7__fdd_PR {
	RF_CapabilityComp_r7__fdd_PR_NOTHING,	/* No components present */
	RF_CapabilityComp_r7__fdd_PR_notSupported,
	RF_CapabilityComp_r7__fdd_PR_supported
} RF_CapabilityComp_r7__fdd_PR;
typedef enum RF_CapabilityComp_r7__tdd384_RF_Capability_PR {
	RF_CapabilityComp_r7__tdd384_RF_Capability_PR_NOTHING,	/* No components present */
	RF_CapabilityComp_r7__tdd384_RF_Capability_PR_notSupported,
	RF_CapabilityComp_r7__tdd384_RF_Capability_PR_supported
} RF_CapabilityComp_r7__tdd384_RF_Capability_PR;
typedef enum RF_CapabilityComp_r7__tdd768_RF_Capability_PR {
	RF_CapabilityComp_r7__tdd768_RF_Capability_PR_NOTHING,	/* No components present */
	RF_CapabilityComp_r7__tdd768_RF_Capability_PR_notSupported,
	RF_CapabilityComp_r7__tdd768_RF_Capability_PR_supported
} RF_CapabilityComp_r7__tdd768_RF_Capability_PR;
typedef enum RF_CapabilityComp_r7__tdd128_RF_Capability_PR {
	RF_CapabilityComp_r7__tdd128_RF_Capability_PR_NOTHING,	/* No components present */
	RF_CapabilityComp_r7__tdd128_RF_Capability_PR_notSupported,
	RF_CapabilityComp_r7__tdd128_RF_Capability_PR_supported
} RF_CapabilityComp_r7__tdd128_RF_Capability_PR;

/* RF-CapabilityComp-r7 */
typedef struct RF_CapabilityComp_r7 {
	struct RF_CapabilityComp_r7__fdd {
		RF_CapabilityComp_r7__fdd_PR present;
		union RF_CapabilityComp_r7__fdd_u {
			NULL_t	 notSupported;
			RF_CapabBandListFDDComp_t	 supported;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} fdd;
	struct RF_CapabilityComp_r7__tdd384_RF_Capability {
		RF_CapabilityComp_r7__tdd384_RF_Capability_PR present;
		union RF_CapabilityComp_r7__tdd384_RF_Capability_u {
			NULL_t	 notSupported;
			RadioFrequencyBandTDDList_t	 supported;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tdd384_RF_Capability;
	struct RF_CapabilityComp_r7__tdd768_RF_Capability {
		RF_CapabilityComp_r7__tdd768_RF_Capability_PR present;
		union RF_CapabilityComp_r7__tdd768_RF_Capability_u {
			NULL_t	 notSupported;
			RadioFrequencyBandTDDList_t	 supported;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tdd768_RF_Capability;
	struct RF_CapabilityComp_r7__tdd128_RF_Capability {
		RF_CapabilityComp_r7__tdd128_RF_Capability_PR present;
		union RF_CapabilityComp_r7__tdd128_RF_Capability_u {
			NULL_t	 notSupported;
			RadioFrequencyBandTDDList_t	 supported;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tdd128_RF_Capability;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RF_CapabilityComp_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RF_CapabilityComp_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_RF_CapabilityComp_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_RF_CapabilityComp_r7_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RF_CapabilityComp_r7_H_ */
#include <asn_internal.h>
