/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_RRCConnectionRequest_H_
#define	_RRCConnectionRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitialUE-Identity.h"
#include "EstablishmentCause.h"
#include "ProtocolErrorIndicator.h"
#include "RRCConnectionRequest-v3d0ext-IEs.h"
#include "RRCConnectionRequest-v4b0ext-IEs.h"
#include "RRCConnectionRequest-v590ext-IEs.h"
#include "RRCConnectionRequest-v690ext-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasuredResultsOnRACH;

/* RRCConnectionRequest */
typedef struct RRCConnectionRequest {
	InitialUE_Identity_t	 initialUE_Identity;
	EstablishmentCause_t	 establishmentCause;
	ProtocolErrorIndicator_t	 protocolErrorIndicator;
	struct MeasuredResultsOnRACH	*measuredResultsOnRACH	/* OPTIONAL */;
	struct RRCConnectionRequest__v3d0NonCriticalExtensions {
		RRCConnectionRequest_v3d0ext_IEs_t	 rRCConnectionRequest_v3d0ext;
		struct RRCConnectionRequest__v3d0NonCriticalExtensions__v4b0NonCriticalExtensions {
			RRCConnectionRequest_v4b0ext_IEs_t	 rrcConnectionRequest_v4b0ext;
			struct RRCConnectionRequest__v3d0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions {
				RRCConnectionRequest_v590ext_IEs_t	 rrcConnectionRequest_v590ext;
				struct RRCConnectionRequest__v3d0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions {
					RRCConnectionRequest_v690ext_IEs_t	 rrcConnectionRequest_v690ext;
					struct RRCConnectionRequest__v3d0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__nonCriticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *nonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *v690NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *v590NonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *v4b0NonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *v3d0NonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRequest_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionRequest_H_ */
#include <asn_internal.h>
