/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_RRCConnectionSetup_H_
#define	_RRCConnectionSetup_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCConnectionSetup-r3-IEs.h"
#include <BIT_STRING.h>
#include "RRCConnectionSetup-v4b0ext-IEs.h"
#include "RRCConnectionSetup-v590ext-IEs.h"
#include "RRCConnectionSetup-v690ext-IEs.h"
#include "RRCConnectionSetup-v7xyext-IEs.h"
#include <constr_SEQUENCE.h>
#include "InitialUE-Identity.h"
#include "RRC-TransactionIdentifier.h"
#include "RRCConnectionSetup-r4-IEs.h"
#include "RRCConnectionSetup-r5-IEs.h"
#include "RRCConnectionSetup-r6-IEs.h"
#include "RRCConnectionSetup-r7-IEs.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionSetup_PR {
	RRCConnectionSetup_PR_NOTHING,	/* No components present */
	RRCConnectionSetup_PR_r3,
	RRCConnectionSetup_PR_later_than_r3
} RRCConnectionSetup_PR;
typedef enum RRCConnectionSetup__later_than_r3__criticalExtensions_PR {
	RRCConnectionSetup__later_than_r3__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionSetup__later_than_r3__criticalExtensions_PR_r4,
	RRCConnectionSetup__later_than_r3__criticalExtensions_PR_criticalExtensions
} RRCConnectionSetup__later_than_r3__criticalExtensions_PR;
typedef enum RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_PR {
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_PR_r5,
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_PR_criticalExtensions
} RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_PR;
typedef enum RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR_r6,
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR;
typedef enum RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR {
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_r7,
	RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR_criticalExtensions
} RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR;

/* RRCConnectionSetup */
typedef struct RRCConnectionSetup {
	RRCConnectionSetup_PR present;
	union RRCConnectionSetup_u {
		struct RRCConnectionSetup__r3 {
			RRCConnectionSetup_r3_IEs_t	 rrcConnectionSetup_r3;
			struct RRCConnectionSetup__r3__laterNonCriticalExtensions {
				BIT_STRING_t	*rrcConnectionSetup_r3_add_ext	/* OPTIONAL */;
				struct RRCConnectionSetup__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions {
					RRCConnectionSetup_v4b0ext_IEs_t	 rrcConnectionSetup_v4b0ext;
					struct RRCConnectionSetup__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions {
						RRCConnectionSetup_v590ext_IEs_t	 rrcConnectionSetup_v590ext;
						struct RRCConnectionSetup__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions {
							RRCConnectionSetup_v690ext_IEs_t	 rrcConnectionSetup_v690ext;
							struct RRCConnectionSetup__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions {
								RRCConnectionSetup_v7xyext_IEs_t	 rrcConnectionSetup_v7xyext;
								struct RRCConnectionSetup__r3__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions__nonCriticalExtensions {
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *nonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v7xyNonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v690NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *v590NonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *v4b0NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct RRCConnectionSetup__later_than_r3 {
			InitialUE_Identity_t	 initialUE_Identity;
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct RRCConnectionSetup__later_than_r3__criticalExtensions {
				RRCConnectionSetup__later_than_r3__criticalExtensions_PR present;
				union RRCConnectionSetup__later_than_r3__criticalExtensions_u {
					struct RRCConnectionSetup__later_than_r3__criticalExtensions__r4 {
						RRCConnectionSetup_r4_IEs_t	 rrcConnectionSetup_r4;
						struct RRCConnectionSetup__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions {
							BIT_STRING_t	*rrcConnectionSetup_r4_add_ext	/* OPTIONAL */;
							struct RRCConnectionSetup__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtensions {
								RRCConnectionSetup_v590ext_IEs_t	 rrcConnectionSetup_v590ext;
								struct RRCConnectionSetup__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions {
									RRCConnectionSetup_v690ext_IEs_t	 rrcConnectionSetup_v690ext;
									struct RRCConnectionSetup__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions {
										RRCConnectionSetup_v7xyext_IEs_t	 rrcConnectionSetup_v7xyext;
										struct RRCConnectionSetup__later_than_r3__criticalExtensions__r4__v4d0NonCriticalExtensions__v590NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions__nonCriticalExtensions {
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *nonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *v7xyNonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v690NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v590NonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v4d0NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r4;
					struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions {
						RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_PR present;
						union RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions_u {
							struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__r5 {
								RRCConnectionSetup_r5_IEs_t	 rrcConnectionSetup_r5;
								BIT_STRING_t	*rrcConnectionSetup_r5_add_ext	/* OPTIONAL */;
								struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__r5__v690NonCriticalExtensions {
									RRCConnectionSetup_v690ext_IEs_t	 rrcConnectionSetup_v690ext;
									struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__r5__v690NonCriticalExtensions__v7xyNonCriticalExtensions {
										RRCConnectionSetup_v7xyext_IEs_t	 rrcConnectionSetup_v7xyext;
										struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__r5__v690NonCriticalExtensions__v7xyNonCriticalExtensions__nonCriticalExtensions {
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *nonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *v7xyNonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v690NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} r5;
							struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions {
								RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
								union RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions_u {
									struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6 {
										RRCConnectionSetup_r6_IEs_t	 rrcConnectionSetup_r6;
										BIT_STRING_t	*rrcConnectionSetup_r6_add_ext	/* OPTIONAL */;
										struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6__v7xyNonCriticalExtensions {
											RRCConnectionSetup_v7xyext_IEs_t	 rrcConnectionSetup_v7xyext;
											struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__r6__v7xyNonCriticalExtensions__nonCriticalExtensions {
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} *nonCriticalExtensions;
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *v7xyNonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} r6;
									struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
										RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_PR present;
										union RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions_u {
											struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7 {
												RRCConnectionSetup_r7_IEs_t	 rrcConnectionSetup_r7;
												BIT_STRING_t	*rrcConnectionSetup_r7_add_ext	/* OPTIONAL */;
												struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__r7__nonCriticalExtensions {
													
													/* Context for parsing across buffer boundaries */
													asn_struct_ctx_t _asn_ctx;
												} *nonCriticalExtensions;
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} r7;
											struct RRCConnectionSetup__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions__criticalExtensions {
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} criticalExtensions;
										} choice;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} criticalExtensions;
								} choice;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} criticalExtensions;
						} choice;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionSetup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetup;
extern asn_CHOICE_specifics_t asn_SPC_RRCConnectionSetup_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionSetup_1[2];
extern asn_per_constraints_t asn_PER_type_RRCConnectionSetup_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionSetup_H_ */
#include <asn_internal.h>
