/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_SCCPCH_SystemInformation_r7_H_
#define	_SCCPCH_SystemInformation_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecondaryCCPCH-Info-r7.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TFCS;
struct FACH_PCH_InformationList;
struct PICH_Info_r7;

/* SCCPCH-SystemInformation-r7 */
typedef struct SCCPCH_SystemInformation_r7 {
	SecondaryCCPCH_Info_r7_t	 secondaryCCPCH_Info;
	struct TFCS	*tfcs	/* OPTIONAL */;
	struct FACH_PCH_InformationList	*fach_PCH_InformationList	/* OPTIONAL */;
	struct PICH_Info_r7	*pich_Info	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCCPCH_SystemInformation_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCCPCH_SystemInformation_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_SCCPCH_SystemInformation_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_SCCPCH_SystemInformation_r7_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SCCPCH_SystemInformation_r7_H_ */
#include <asn_internal.h>
