/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "SYNC-UL-Info-r4.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_sync_UL_Codes_Bitmap_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_prxUpPCHdes_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 62)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_powerRampStep_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_mmax_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_max_SYNC_UL_Transmissions_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_max_SYNC_UL_Transmissions_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sync_UL_Codes_Bitmap_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	8	/* (SIZE(8..8)) */};
static asn_per_constraints_t asn_PER_memb_sync_UL_Codes_Bitmap_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_prxUpPCHdes_constr_11 CC_NOTUSED = {
	{ 1, 1 }	/* (0..62) */,
	-1};
static asn_per_constraints_t asn_PER_memb_prxUpPCHdes_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  62 }	/* (0..62) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_powerRampStep_constr_12 CC_NOTUSED = {
	{ 1, 1 }	/* (0..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_powerRampStep_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_mmax_constr_18 CC_NOTUSED = {
	{ 1, 1 }	/* (1..32) */,
	-1};
static asn_per_constraints_t asn_PER_memb_mmax_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (1..32) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_max_SYNC_UL_Transmissions_value2enum_13[] = {
	{ 0,	3,	"tr1" },
	{ 1,	3,	"tr2" },
	{ 2,	3,	"tr4" },
	{ 3,	3,	"tr8" }
};
static const unsigned int asn_MAP_max_SYNC_UL_Transmissions_enum2value_13[] = {
	0,	/* tr1(0) */
	1,	/* tr2(1) */
	2,	/* tr4(2) */
	3	/* tr8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_max_SYNC_UL_Transmissions_specs_13 = {
	asn_MAP_max_SYNC_UL_Transmissions_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_max_SYNC_UL_Transmissions_enum2value_13,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_max_SYNC_UL_Transmissions_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_max_SYNC_UL_Transmissions_13 = {
	"max-SYNC-UL-Transmissions",
	"max-SYNC-UL-Transmissions",
	&asn_OP_NativeEnumerated,
	asn_DEF_max_SYNC_UL_Transmissions_tags_13,
	sizeof(asn_DEF_max_SYNC_UL_Transmissions_tags_13)
		/sizeof(asn_DEF_max_SYNC_UL_Transmissions_tags_13[0]) - 1, /* 1 */
	asn_DEF_max_SYNC_UL_Transmissions_tags_13,	/* Same as above */
	sizeof(asn_DEF_max_SYNC_UL_Transmissions_tags_13)
		/sizeof(asn_DEF_max_SYNC_UL_Transmissions_tags_13[0]), /* 2 */
	{ &asn_OER_type_max_SYNC_UL_Transmissions_constr_13, &asn_PER_type_max_SYNC_UL_Transmissions_constr_13, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_max_SYNC_UL_Transmissions_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SYNC_UL_Info_r4_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SYNC_UL_Info_r4, sync_UL_Codes_Bitmap),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_sync_UL_Codes_Bitmap_constr_2, &asn_PER_memb_sync_UL_Codes_Bitmap_constr_2,  memb_sync_UL_Codes_Bitmap_constraint_1 },
		0, 0, /* No default value */
		"sync-UL-Codes-Bitmap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SYNC_UL_Info_r4, prxUpPCHdes),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_prxUpPCHdes_constr_11, &asn_PER_memb_prxUpPCHdes_constr_11,  memb_prxUpPCHdes_constraint_1 },
		0, 0, /* No default value */
		"prxUpPCHdes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SYNC_UL_Info_r4, powerRampStep),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_powerRampStep_constr_12, &asn_PER_memb_powerRampStep_constr_12,  memb_powerRampStep_constraint_1 },
		0, 0, /* No default value */
		"powerRampStep"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SYNC_UL_Info_r4, max_SYNC_UL_Transmissions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_max_SYNC_UL_Transmissions_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"max-SYNC-UL-Transmissions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SYNC_UL_Info_r4, mmax),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_mmax_constr_18, &asn_PER_memb_mmax_constr_18,  memb_mmax_constraint_1 },
		0, 0, /* No default value */
		"mmax"
		},
};
static const ber_tlv_tag_t asn_DEF_SYNC_UL_Info_r4_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SYNC_UL_Info_r4_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sync-UL-Codes-Bitmap */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* prxUpPCHdes */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* powerRampStep */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* max-SYNC-UL-Transmissions */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* mmax */
};
asn_SEQUENCE_specifics_t asn_SPC_SYNC_UL_Info_r4_specs_1 = {
	sizeof(struct SYNC_UL_Info_r4),
	offsetof(struct SYNC_UL_Info_r4, _asn_ctx),
	asn_MAP_SYNC_UL_Info_r4_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SYNC_UL_Info_r4 = {
	"SYNC-UL-Info-r4",
	"SYNC-UL-Info-r4",
	&asn_OP_SEQUENCE,
	asn_DEF_SYNC_UL_Info_r4_tags_1,
	sizeof(asn_DEF_SYNC_UL_Info_r4_tags_1)
		/sizeof(asn_DEF_SYNC_UL_Info_r4_tags_1[0]), /* 1 */
	asn_DEF_SYNC_UL_Info_r4_tags_1,	/* Same as above */
	sizeof(asn_DEF_SYNC_UL_Info_r4_tags_1)
		/sizeof(asn_DEF_SYNC_UL_Info_r4_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SYNC_UL_Info_r4_1,
	5,	/* Elements count */
	&asn_SPC_SYNC_UL_Info_r4_specs_1	/* Additional specs */
};

