/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "SysInfoType5-v7xyext-IEs.h"

#include "PUSCH-SysInfoList-SFN-VHCR.h"
#include "PRACH-SystemInformationList-r7.h"
#include "PDSCH-SysInfoList-r7.h"
#include "SCCPCH-SystemInformationList-r7.h"
static asn_oer_constraints_t asn_OER_type_sccpch_SystemInformation_MBMS_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_sccpch_SystemInformation_MBMS_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_sccpch_SystemInformation_MBMS_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5_v7xyext_IEs__sccpch_SystemInformation_MBMS, choice.mcchOnSCCPCHusedForNonMBMS),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_MCCH_ConfigurationInfo_r6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mcchOnSCCPCHusedForNonMBMS"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5_v7xyext_IEs__sccpch_SystemInformation_MBMS, choice.mcchOnSCCPCHusedOnlyForMBMS),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCCPCH_SystemInformation_MBMS_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mcchOnSCCPCHusedOnlyForMBMS"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_sccpch_SystemInformation_MBMS_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mcchOnSCCPCHusedForNonMBMS */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* mcchOnSCCPCHusedOnlyForMBMS */
};
static asn_CHOICE_specifics_t asn_SPC_sccpch_SystemInformation_MBMS_specs_5 = {
	sizeof(struct SysInfoType5_v7xyext_IEs__sccpch_SystemInformation_MBMS),
	offsetof(struct SysInfoType5_v7xyext_IEs__sccpch_SystemInformation_MBMS, _asn_ctx),
	offsetof(struct SysInfoType5_v7xyext_IEs__sccpch_SystemInformation_MBMS, present),
	sizeof(((struct SysInfoType5_v7xyext_IEs__sccpch_SystemInformation_MBMS *)0)->present),
	asn_MAP_sccpch_SystemInformation_MBMS_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sccpch_SystemInformation_MBMS_5 = {
	"sccpch-SystemInformation-MBMS",
	"sccpch-SystemInformation-MBMS",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_sccpch_SystemInformation_MBMS_constr_5, &asn_PER_type_sccpch_SystemInformation_MBMS_constr_5, CHOICE_constraint },
	asn_MBR_sccpch_SystemInformation_MBMS_5,
	2,	/* Elements count */
	&asn_SPC_sccpch_SystemInformation_MBMS_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SysInfoType5_v7xyext_IEs_1[] = {
	{ ATF_POINTER, 5, offsetof(struct SysInfoType5_v7xyext_IEs, pusch_SysInfoList_SFN_VHCR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_SysInfoList_SFN_VHCR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-SysInfoList-SFN-VHCR"
		},
	{ ATF_POINTER, 4, offsetof(struct SysInfoType5_v7xyext_IEs, prach_SystemInformationList_r7),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRACH_SystemInformationList_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prach-SystemInformationList-r7"
		},
	{ ATF_POINTER, 3, offsetof(struct SysInfoType5_v7xyext_IEs, pdsch_SysInfoList_SFN_r7),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_SysInfoList_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-SysInfoList-SFN-r7"
		},
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5_v7xyext_IEs, sccpch_SystemInformation_MBMS),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_sccpch_SystemInformation_MBMS_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sccpch-SystemInformation-MBMS"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5_v7xyext_IEs, sCCPCH_SystemInformationList_r7),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCCPCH_SystemInformationList_r7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCCPCH-SystemInformationList-r7"
		},
};
static const int asn_MAP_SysInfoType5_v7xyext_IEs_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SysInfoType5_v7xyext_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SysInfoType5_v7xyext_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pusch-SysInfoList-SFN-VHCR */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* prach-SystemInformationList-r7 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pdsch-SysInfoList-SFN-r7 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sccpch-SystemInformation-MBMS */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* sCCPCH-SystemInformationList-r7 */
};
asn_SEQUENCE_specifics_t asn_SPC_SysInfoType5_v7xyext_IEs_specs_1 = {
	sizeof(struct SysInfoType5_v7xyext_IEs),
	offsetof(struct SysInfoType5_v7xyext_IEs, _asn_ctx),
	asn_MAP_SysInfoType5_v7xyext_IEs_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SysInfoType5_v7xyext_IEs_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SysInfoType5_v7xyext_IEs = {
	"SysInfoType5-v7xyext-IEs",
	"SysInfoType5-v7xyext-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_SysInfoType5_v7xyext_IEs_tags_1,
	sizeof(asn_DEF_SysInfoType5_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_SysInfoType5_v7xyext_IEs_tags_1[0]), /* 1 */
	asn_DEF_SysInfoType5_v7xyext_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_SysInfoType5_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_SysInfoType5_v7xyext_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SysInfoType5_v7xyext_IEs_1,
	5,	/* Elements count */
	&asn_SPC_SysInfoType5_v7xyext_IEs_specs_1	/* Additional specs */
};

