/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "SysInfoType5.h"

#include "PrimaryCCPCH-Info.h"
#include "CBS-DRX-Level1Information.h"
#include "PUSCH-SysInfoList-SFN.h"
#include "PDSCH-SysInfoList-SFN.h"
#include "SysInfoType5-v4b0ext-IEs.h"
#include "SysInfoType5-v590ext-IEs.h"
#include "SysInfoType5-v650ext-IEs.h"
#include "SysInfoType5-v680ext-IEs.h"
static asn_oer_constraints_t asn_OER_type_modeSpecificInfo_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_modeSpecificInfo_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_fdd_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5__modeSpecificInfo__fdd, aich_PowerOffset),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AICH_PowerOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aich-PowerOffset"
		},
};
static const ber_tlv_tag_t asn_DEF_fdd_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_fdd_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* aich-PowerOffset */
};
static asn_SEQUENCE_specifics_t asn_SPC_fdd_specs_5 = {
	sizeof(struct SysInfoType5__modeSpecificInfo__fdd),
	offsetof(struct SysInfoType5__modeSpecificInfo__fdd, _asn_ctx),
	asn_MAP_fdd_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fdd_5 = {
	"fdd",
	"fdd",
	&asn_OP_SEQUENCE,
	asn_DEF_fdd_tags_5,
	sizeof(asn_DEF_fdd_tags_5)
		/sizeof(asn_DEF_fdd_tags_5[0]) - 1, /* 1 */
	asn_DEF_fdd_tags_5,	/* Same as above */
	sizeof(asn_DEF_fdd_tags_5)
		/sizeof(asn_DEF_fdd_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_fdd_5,
	1,	/* Elements count */
	&asn_SPC_fdd_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tdd_7[] = {
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5__modeSpecificInfo__tdd, pusch_SysInfoList_SFN),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_SysInfoList_SFN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-SysInfoList-SFN"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__modeSpecificInfo__tdd, pdsch_SysInfoList_SFN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_SysInfoList_SFN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-SysInfoList-SFN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5__modeSpecificInfo__tdd, openLoopPowerControl_TDD),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenLoopPowerControl_TDD,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"openLoopPowerControl-TDD"
		},
};
static const int asn_MAP_tdd_oms_7[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_tdd_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tdd_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pusch-SysInfoList-SFN */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pdsch-SysInfoList-SFN */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* openLoopPowerControl-TDD */
};
static asn_SEQUENCE_specifics_t asn_SPC_tdd_specs_7 = {
	sizeof(struct SysInfoType5__modeSpecificInfo__tdd),
	offsetof(struct SysInfoType5__modeSpecificInfo__tdd, _asn_ctx),
	asn_MAP_tdd_tag2el_7,
	3,	/* Count of tags in the map */
	asn_MAP_tdd_oms_7,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdd_7 = {
	"tdd",
	"tdd",
	&asn_OP_SEQUENCE,
	asn_DEF_tdd_tags_7,
	sizeof(asn_DEF_tdd_tags_7)
		/sizeof(asn_DEF_tdd_tags_7[0]) - 1, /* 1 */
	asn_DEF_tdd_tags_7,	/* Same as above */
	sizeof(asn_DEF_tdd_tags_7)
		/sizeof(asn_DEF_tdd_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tdd_7,
	3,	/* Elements count */
	&asn_SPC_tdd_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_modeSpecificInfo_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5__modeSpecificInfo, choice.fdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_fdd_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5__modeSpecificInfo, choice.tdd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_tdd_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_modeSpecificInfo_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd */
};
static asn_CHOICE_specifics_t asn_SPC_modeSpecificInfo_specs_4 = {
	sizeof(struct SysInfoType5__modeSpecificInfo),
	offsetof(struct SysInfoType5__modeSpecificInfo, _asn_ctx),
	offsetof(struct SysInfoType5__modeSpecificInfo, present),
	sizeof(((struct SysInfoType5__modeSpecificInfo *)0)->present),
	asn_MAP_modeSpecificInfo_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_modeSpecificInfo_4 = {
	"modeSpecificInfo",
	"modeSpecificInfo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_modeSpecificInfo_constr_4, &asn_PER_type_modeSpecificInfo_constr_4, CHOICE_constraint },
	asn_MBR_modeSpecificInfo_4,
	2,	/* Elements count */
	&asn_SPC_modeSpecificInfo_specs_4	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_27 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_27 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_27,
	sizeof(asn_DEF_nonCriticalExtensions_tags_27)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_27[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_27,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_27)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_27[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v7xyNonCriticalExtensions_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions, sysInfoType5_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType5_v7xyext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType5-v7xyext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_27,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v7xyNonCriticalExtensions_oms_25[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v7xyNonCriticalExtensions_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v7xyNonCriticalExtensions_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType5-v7xyext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v7xyNonCriticalExtensions_specs_25 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions__v7xyNonCriticalExtensions, _asn_ctx),
	asn_MAP_v7xyNonCriticalExtensions_tag2el_25,
	2,	/* Count of tags in the map */
	asn_MAP_v7xyNonCriticalExtensions_oms_25,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v7xyNonCriticalExtensions_25 = {
	"v7xyNonCriticalExtensions",
	"v7xyNonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v7xyNonCriticalExtensions_tags_25,
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_25)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_25[0]) - 1, /* 1 */
	asn_DEF_v7xyNonCriticalExtensions_tags_25,	/* Same as above */
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_25)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_25[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v7xyNonCriticalExtensions_25,
	2,	/* Elements count */
	&asn_SPC_v7xyNonCriticalExtensions_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions, sysInfoType5_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType5_v690ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType5-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions, v7xyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v7xyNonCriticalExtensions_25,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v7xyNonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_23[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType5-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v7xyNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_23 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions__v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_23,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_23,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_23 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v690NonCriticalExtensions_tags_23,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_23)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_23[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_23,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_23)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_23[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v690NonCriticalExtensions_23,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v680NonCriticalExtensions_21[] = {
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions, sysInfoType5_v680ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType5_v680ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType5-v680ext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v680NonCriticalExtensions_oms_21[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_v680NonCriticalExtensions_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v680NonCriticalExtensions_tag2el_21[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType5-v680ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v680NonCriticalExtensions_specs_21 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions__v680NonCriticalExtensions, _asn_ctx),
	asn_MAP_v680NonCriticalExtensions_tag2el_21,
	2,	/* Count of tags in the map */
	asn_MAP_v680NonCriticalExtensions_oms_21,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v680NonCriticalExtensions_21 = {
	"v680NonCriticalExtensions",
	"v680NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v680NonCriticalExtensions_tags_21,
	sizeof(asn_DEF_v680NonCriticalExtensions_tags_21)
		/sizeof(asn_DEF_v680NonCriticalExtensions_tags_21[0]) - 1, /* 1 */
	asn_DEF_v680NonCriticalExtensions_tags_21,	/* Same as above */
	sizeof(asn_DEF_v680NonCriticalExtensions_tags_21)
		/sizeof(asn_DEF_v680NonCriticalExtensions_tags_21[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v680NonCriticalExtensions_21,
	2,	/* Elements count */
	&asn_SPC_v680NonCriticalExtensions_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v650NonCriticalExtensions_19[] = {
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions, sysInfoType5_v650ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType5_v650ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType5-v650ext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions, v680NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v680NonCriticalExtensions_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v680NonCriticalExtensions"
		},
};
static const int asn_MAP_v650NonCriticalExtensions_oms_19[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_v650NonCriticalExtensions_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v650NonCriticalExtensions_tag2el_19[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType5-v650ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v680NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v650NonCriticalExtensions_specs_19 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v650NonCriticalExtensions, _asn_ctx),
	asn_MAP_v650NonCriticalExtensions_tag2el_19,
	2,	/* Count of tags in the map */
	asn_MAP_v650NonCriticalExtensions_oms_19,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v650NonCriticalExtensions_19 = {
	"v650NonCriticalExtensions",
	"v650NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v650NonCriticalExtensions_tags_19,
	sizeof(asn_DEF_v650NonCriticalExtensions_tags_19)
		/sizeof(asn_DEF_v650NonCriticalExtensions_tags_19[0]) - 1, /* 1 */
	asn_DEF_v650NonCriticalExtensions_tags_19,	/* Same as above */
	sizeof(asn_DEF_v650NonCriticalExtensions_tags_19)
		/sizeof(asn_DEF_v650NonCriticalExtensions_tags_19[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v650NonCriticalExtensions_19,
	2,	/* Elements count */
	&asn_SPC_v650NonCriticalExtensions_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtensions_17[] = {
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions, sysInfoType5_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType5_v590ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType5-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions, v650NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v650NonCriticalExtensions_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v650NonCriticalExtensions"
		},
};
static const int asn_MAP_v590NonCriticalExtensions_oms_17[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtensions_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtensions_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType5-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v650NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtensions_specs_17 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions__v590NonCriticalExtensions, _asn_ctx),
	asn_MAP_v590NonCriticalExtensions_tag2el_17,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtensions_oms_17,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtensions_17 = {
	"v590NonCriticalExtensions",
	"v590NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v590NonCriticalExtensions_tags_17,
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_17)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_17[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtensions_tags_17,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_17)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v590NonCriticalExtensions_17,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtensions_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_15[] = {
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions, sysInfoType5_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType5_v4b0ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType5-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5__v4b0NonCriticalExtensions, v590NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtensions_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v590NonCriticalExtensions"
		},
};
static const int asn_MAP_v4b0NonCriticalExtensions_oms_15[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType5-v4b0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_15 = {
	sizeof(struct SysInfoType5__v4b0NonCriticalExtensions),
	offsetof(struct SysInfoType5__v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_15,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_15,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_15 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v4b0NonCriticalExtensions_tags_15,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_15)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_15[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_15,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_15)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_15[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v4b0NonCriticalExtensions_15,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SysInfoType5_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5, sib6indicator),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sib6indicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5, pich_PowerOffset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PICH_PowerOffset,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pich-PowerOffset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5, modeSpecificInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_modeSpecificInfo_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"modeSpecificInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5, primaryCCPCH_Info),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PrimaryCCPCH_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"primaryCCPCH-Info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5, prach_SystemInformationList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRACH_SystemInformationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prach-SystemInformationList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType5, sCCPCH_SystemInformationList),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCCPCH_SystemInformationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCCPCH-SystemInformationList"
		},
	{ ATF_POINTER, 2, offsetof(struct SysInfoType5, cbs_DRX_Level1Information),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CBS_DRX_Level1Information,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cbs-DRX-Level1Information"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType5, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v4b0NonCriticalExtensions"
		},
};
static const int asn_MAP_SysInfoType5_oms_1[] = { 3, 6, 7 };
static const ber_tlv_tag_t asn_DEF_SysInfoType5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SysInfoType5_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sib6indicator */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pich-PowerOffset */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* modeSpecificInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* primaryCCPCH-Info */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* prach-SystemInformationList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sCCPCH-SystemInformationList */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* cbs-DRX-Level1Information */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* v4b0NonCriticalExtensions */
};
asn_SEQUENCE_specifics_t asn_SPC_SysInfoType5_specs_1 = {
	sizeof(struct SysInfoType5),
	offsetof(struct SysInfoType5, _asn_ctx),
	asn_MAP_SysInfoType5_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_SysInfoType5_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SysInfoType5 = {
	"SysInfoType5",
	"SysInfoType5",
	&asn_OP_SEQUENCE,
	asn_DEF_SysInfoType5_tags_1,
	sizeof(asn_DEF_SysInfoType5_tags_1)
		/sizeof(asn_DEF_SysInfoType5_tags_1[0]), /* 1 */
	asn_DEF_SysInfoType5_tags_1,	/* Same as above */
	sizeof(asn_DEF_SysInfoType5_tags_1)
		/sizeof(asn_DEF_SysInfoType5_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SysInfoType5_1,
	8,	/* Elements count */
	&asn_SPC_SysInfoType5_specs_1	/* Additional specs */
};

