/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "SysInfoType15.h"

#include "UE-Positioning-CipherParameters.h"
#include "BadSatList.h"
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_8 = {
	sizeof(struct SysInfoType15__v4b0NonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct SysInfoType15__v4b0NonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_8 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_8,
	sizeof(asn_DEF_nonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType15__v4b0NonCriticalExtensions, sysInfoType15_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType15_v4b0ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sysInfoType15-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType15__v4b0NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v4b0NonCriticalExtensions_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType15-v4b0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_6 = {
	sizeof(struct SysInfoType15__v4b0NonCriticalExtensions),
	offsetof(struct SysInfoType15__v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_6 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v4b0NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v4b0NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SysInfoType15_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SysInfoType15, ue_positioning_GPS_CipherParameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_CipherParameters,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-positioning-GPS-CipherParameters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType15, ue_positioning_GPS_ReferenceLocation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReferenceLocation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-positioning-GPS-ReferenceLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType15, ue_positioning_GPS_ReferenceTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_GPS_ReferenceTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-positioning-GPS-ReferenceTime"
		},
	{ ATF_POINTER, 2, offsetof(struct SysInfoType15, ue_positioning_GPS_Real_timeIntegrity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BadSatList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-positioning-GPS-Real-timeIntegrity"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType15, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v4b0NonCriticalExtensions"
		},
};
static const int asn_MAP_SysInfoType15_oms_1[] = { 0, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SysInfoType15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SysInfoType15_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-positioning-GPS-CipherParameters */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ue-positioning-GPS-ReferenceLocation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ue-positioning-GPS-ReferenceTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ue-positioning-GPS-Real-timeIntegrity */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* v4b0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_SysInfoType15_specs_1 = {
	sizeof(struct SysInfoType15),
	offsetof(struct SysInfoType15, _asn_ctx),
	asn_MAP_SysInfoType15_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SysInfoType15_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SysInfoType15 = {
	"SysInfoType15",
	"SysInfoType15",
	&asn_OP_SEQUENCE,
	asn_DEF_SysInfoType15_tags_1,
	sizeof(asn_DEF_SysInfoType15_tags_1)
		/sizeof(asn_DEF_SysInfoType15_tags_1[0]), /* 1 */
	asn_DEF_SysInfoType15_tags_1,	/* Same as above */
	sizeof(asn_DEF_SysInfoType15_tags_1)
		/sizeof(asn_DEF_SysInfoType15_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SysInfoType15_1,
	5,	/* Elements count */
	&asn_SPC_SysInfoType15_specs_1	/* Additional specs */
};

