/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_SysInfoType18_H_
#define	_SysInfoType18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PLMNIdentitiesOfNeighbourCells;

/* SysInfoType18 */
typedef struct SysInfoType18 {
	struct PLMNIdentitiesOfNeighbourCells	*idleModePLMNIdentities	/* OPTIONAL */;
	struct PLMNIdentitiesOfNeighbourCells	*connectedModePLMNIdentities	/* OPTIONAL */;
	struct SysInfoType18__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType18;

#ifdef __cplusplus
}
#endif

#endif	/* _SysInfoType18_H_ */
#include <asn_internal.h>
