/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_SysInfoType15_3_H_
#define	_SysInfoType15_3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_Positioning_GPS_Almanac;
struct UE_Positioning_GPS_IonosphericModel;
struct UE_Positioning_GPS_UTC_Model;

/* SysInfoType15-3 */
typedef struct SysInfoType15_3 {
	long	 transmissionTOW;
	struct UE_Positioning_GPS_Almanac	*ue_positioning_GPS_Almanac	/* OPTIONAL */;
	struct UE_Positioning_GPS_IonosphericModel	*ue_positioning_GPS_IonosphericModel	/* OPTIONAL */;
	struct UE_Positioning_GPS_UTC_Model	*ue_positioning_GPS_UTC_Model	/* OPTIONAL */;
	BIT_STRING_t	*satMask	/* OPTIONAL */;
	BIT_STRING_t	*lsbTOW	/* OPTIONAL */;
	struct SysInfoType15_3__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType15_3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType15_3;

#ifdef __cplusplus
}
#endif

#endif	/* _SysInfoType15_3_H_ */
#include <asn_internal.h>
