/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_SystemInformationChangeIndication_H_
#define	_SystemInformationChangeIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCCH-ModificationInfo.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SystemInformationChangeIndication */
typedef struct SystemInformationChangeIndication {
	BCCH_ModificationInfo_t	 bcch_ModificationInfo;
	struct SystemInformationChangeIndication__laterNonCriticalExtensions {
		BIT_STRING_t	*systemInformationChangeIndication_r3_add_ext	/* OPTIONAL */;
		struct SystemInformationChangeIndication__laterNonCriticalExtensions__nonCriticalExtensions {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laterNonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationChangeIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformationChangeIndication;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemInformationChangeIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemInformationChangeIndication_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformationChangeIndication_H_ */
#include <asn_internal.h>
