/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "TransportChannelReconfigurationComplete-v7xyext-IEs.h"

#include "EXT-UL-TimingAdvance.h"
asn_TYPE_member_t asn_MBR_TransportChannelReconfigurationComplete_v7xyext_IEs_1[] = {
	{ ATF_POINTER, 1, offsetof(struct TransportChannelReconfigurationComplete_v7xyext_IEs, ext_ul_TimingAdvance),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EXT_UL_TimingAdvance,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext-ul-TimingAdvance"
		},
};
static const int asn_MAP_TransportChannelReconfigurationComplete_v7xyext_IEs_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TransportChannelReconfigurationComplete_v7xyext_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ext-ul-TimingAdvance */
};
asn_SEQUENCE_specifics_t asn_SPC_TransportChannelReconfigurationComplete_v7xyext_IEs_specs_1 = {
	sizeof(struct TransportChannelReconfigurationComplete_v7xyext_IEs),
	offsetof(struct TransportChannelReconfigurationComplete_v7xyext_IEs, _asn_ctx),
	asn_MAP_TransportChannelReconfigurationComplete_v7xyext_IEs_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_TransportChannelReconfigurationComplete_v7xyext_IEs_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs = {
	"TransportChannelReconfigurationComplete-v7xyext-IEs",
	"TransportChannelReconfigurationComplete-v7xyext-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1,
	sizeof(asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1[0]), /* 1 */
	asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1)
		/sizeof(asn_DEF_TransportChannelReconfigurationComplete_v7xyext_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TransportChannelReconfigurationComplete_v7xyext_IEs_1,
	1,	/* Elements count */
	&asn_SPC_TransportChannelReconfigurationComplete_v7xyext_IEs_specs_1	/* Additional specs */
};

