/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_UE_InternalMeasuredResults_r7_H_
#define	_UE_InternalMeasuredResults_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-TransmittedPower.h"
#include <constr_SEQUENCE.h>
#include "UL-TimingAdvance-VHCR.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_InternalMeasuredResults_r7__modeSpecificInfo_PR {
	UE_InternalMeasuredResults_r7__modeSpecificInfo_PR_NOTHING,	/* No components present */
	UE_InternalMeasuredResults_r7__modeSpecificInfo_PR_fdd,
	UE_InternalMeasuredResults_r7__modeSpecificInfo_PR_tdd
} UE_InternalMeasuredResults_r7__modeSpecificInfo_PR;

/* Forward declarations */
struct UE_RX_TX_ReportEntryList;
struct UE_TransmittedPowerTDD_List;

/* UE-InternalMeasuredResults-r7 */
typedef struct UE_InternalMeasuredResults_r7 {
	struct UE_InternalMeasuredResults_r7__modeSpecificInfo {
		UE_InternalMeasuredResults_r7__modeSpecificInfo_PR present;
		union UE_InternalMeasuredResults_r7__modeSpecificInfo_u {
			struct UE_InternalMeasuredResults_r7__modeSpecificInfo__fdd {
				UE_TransmittedPower_t	*ue_TransmittedPowerFDD	/* OPTIONAL */;
				struct UE_RX_TX_ReportEntryList	*ue_RX_TX_ReportEntryList	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct UE_InternalMeasuredResults_r7__modeSpecificInfo__tdd {
				struct UE_TransmittedPowerTDD_List	*ue_TransmittedPowerTDD_List	/* OPTIONAL */;
				UL_TimingAdvance_VHCR_t	*appliedTA	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_InternalMeasuredResults_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_InternalMeasuredResults_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_InternalMeasuredResults_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_InternalMeasuredResults_r7_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_InternalMeasuredResults_r7_H_ */
#include <asn_internal.h>
