/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "UE-Positioning-GPS-MeasurementResults.h"

static int
memb_gps_ReferenceTimeOnly_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 604799999)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_gps_ReferenceTimeOnly_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..604799999) */,
	-1};
static asn_per_constraints_t asn_PER_memb_gps_ReferenceTimeOnly_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 30, -1,  0,  604799999 }	/* (0..604799999) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_referenceTime_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_referenceTime_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_referenceTime_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_Positioning_GPS_MeasurementResults__referenceTime, choice.utran_GPSReferenceTimeResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTRAN_GPSReferenceTimeResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utran-GPSReferenceTimeResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_Positioning_GPS_MeasurementResults__referenceTime, choice.gps_ReferenceTimeOnly),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_gps_ReferenceTimeOnly_constr_4, &asn_PER_memb_gps_ReferenceTimeOnly_constr_4,  memb_gps_ReferenceTimeOnly_constraint_2 },
		0, 0, /* No default value */
		"gps-ReferenceTimeOnly"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_referenceTime_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utran-GPSReferenceTimeResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* gps-ReferenceTimeOnly */
};
static asn_CHOICE_specifics_t asn_SPC_referenceTime_specs_2 = {
	sizeof(struct UE_Positioning_GPS_MeasurementResults__referenceTime),
	offsetof(struct UE_Positioning_GPS_MeasurementResults__referenceTime, _asn_ctx),
	offsetof(struct UE_Positioning_GPS_MeasurementResults__referenceTime, present),
	sizeof(((struct UE_Positioning_GPS_MeasurementResults__referenceTime *)0)->present),
	asn_MAP_referenceTime_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_referenceTime_2 = {
	"referenceTime",
	"referenceTime",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_referenceTime_constr_2, &asn_PER_type_referenceTime_constr_2, CHOICE_constraint },
	asn_MBR_referenceTime_2,
	2,	/* Elements count */
	&asn_SPC_referenceTime_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UE_Positioning_GPS_MeasurementResults_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_Positioning_GPS_MeasurementResults, referenceTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_referenceTime_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_Positioning_GPS_MeasurementResults, gps_MeasurementParamList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPS_MeasurementParamList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gps-MeasurementParamList"
		},
};
static const ber_tlv_tag_t asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_Positioning_GPS_MeasurementResults_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* referenceTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* gps-MeasurementParamList */
};
asn_SEQUENCE_specifics_t asn_SPC_UE_Positioning_GPS_MeasurementResults_specs_1 = {
	sizeof(struct UE_Positioning_GPS_MeasurementResults),
	offsetof(struct UE_Positioning_GPS_MeasurementResults, _asn_ctx),
	asn_MAP_UE_Positioning_GPS_MeasurementResults_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UE_Positioning_GPS_MeasurementResults = {
	"UE-Positioning-GPS-MeasurementResults",
	"UE-Positioning-GPS-MeasurementResults",
	&asn_OP_SEQUENCE,
	asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1,
	sizeof(asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1)
		/sizeof(asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1[0]), /* 1 */
	asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1)
		/sizeof(asn_DEF_UE_Positioning_GPS_MeasurementResults_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UE_Positioning_GPS_MeasurementResults_1,
	2,	/* Elements count */
	&asn_SPC_UE_Positioning_GPS_MeasurementResults_specs_1	/* Additional specs */
};

