/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_UE_Positioning_GPS_AcquisitionAssistance_H_
#define	_UE_Positioning_GPS_AcquisitionAssistance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "AcquisitionSatInfoList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UTRAN_GPSReferenceTime;

/* UE-Positioning-GPS-AcquisitionAssistance */
typedef struct UE_Positioning_GPS_AcquisitionAssistance {
	long	 gps_ReferenceTime;
	struct UTRAN_GPSReferenceTime	*utran_GPSReferenceTime	/* OPTIONAL */;
	AcquisitionSatInfoList_t	 satelliteInformationList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Positioning_GPS_AcquisitionAssistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_GPS_AcquisitionAssistance;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_Positioning_GPS_AcquisitionAssistance_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_Positioning_GPS_AcquisitionAssistance_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_Positioning_GPS_AcquisitionAssistance_H_ */
#include <asn_internal.h>
