/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_UE_RadioAccessCapability_v7xyext_H_
#define	_UE_RadioAccessCapability_v7xyext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RF_Capability_r7;
struct PhysicalChannelCapability_r7;

/* UE-RadioAccessCapability-v7xyext */
typedef struct UE_RadioAccessCapability_v7xyext {
	struct RF_Capability_r7	*rf_Capability	/* OPTIONAL */;
	struct PhysicalChannelCapability_r7	*physicalChannelCapability_r7	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_RadioAccessCapability_v7xyext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioAccessCapability_v7xyext;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_RadioAccessCapability_v7xyext_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_RadioAccessCapability_v7xyext_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RadioAccessCapability_v7xyext_H_ */
#include <asn_internal.h>
