/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_UE_RadioAccessCapabilityComp_r7_H_
#define	_UE_RadioAccessCapabilityComp_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "RF-CapabilityComp-r7.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-RadioAccessCapabilityComp-r7 */
typedef struct UE_RadioAccessCapabilityComp_r7 {
	BOOLEAN_t	 totalAM_RLCMemoryExceeds10kB;
	RF_CapabilityComp_r7_t	 rf_CapabilityComp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_RadioAccessCapabilityComp_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioAccessCapabilityComp_r7;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_RadioAccessCapabilityComp_r7_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_RadioAccessCapabilityComp_r7_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RadioAccessCapabilityComp_r7_H_ */
#include <asn_internal.h>
