/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#ifndef	_UTRANMobilityInformationConfirm_H_
#define	_UTRANMobilityInformationConfirm_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC-TransactionIdentifier.h"
#include "ActivationTime.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntegrityProtActivationInfo;
struct RB_ActivationTimeInfoList;
struct UL_CounterSynchronisationInfo;

/* UTRANMobilityInformationConfirm */
typedef struct UTRANMobilityInformationConfirm {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct IntegrityProtActivationInfo	*ul_IntegProtActivationInfo	/* OPTIONAL */;
	ActivationTime_t	*count_C_ActivationTime	/* OPTIONAL */;
	struct RB_ActivationTimeInfoList	*dummy	/* OPTIONAL */;
	struct UL_CounterSynchronisationInfo	*ul_CounterSynchronisationInfo	/* OPTIONAL */;
	struct UTRANMobilityInformationConfirm__laterNonCriticalExtensions {
		BIT_STRING_t	*utranMobilityInformationConfirm_r3_add_ext	/* OPTIONAL */;
		struct UTRANMobilityInformationConfirm__laterNonCriticalExtensions__nonCriticalExtensions {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laterNonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UTRANMobilityInformationConfirm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UTRANMobilityInformationConfirm;
extern asn_SEQUENCE_specifics_t asn_SPC_UTRANMobilityInformationConfirm_specs_1;
extern asn_TYPE_member_t asn_MBR_UTRANMobilityInformationConfirm_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _UTRANMobilityInformationConfirm_H_ */
#include <asn_internal.h>
