/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrcstr.asn1"
 * 	`asn1c -D src -fcompound-names -fno-include-deps`
 */

#include "UTRANMobilityInformation.h"

static asn_oer_constraints_t asn_OER_type_criticalExtensions_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_UTRANMobilityInformation_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_UTRANMobilityInformation_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_10 = {
	sizeof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_10 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_10,
	sizeof(asn_DEF_nonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions, utranMobilityInformation_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UtranMobilityInformation_v690ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranMobilityInformation-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utranMobilityInformation-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_8 = {
	sizeof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions),
	offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_8 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v690NonCriticalExtensions_tags_8,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v690NonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_laterNonCriticalExtensions_6[] = {
	{ ATF_POINTER, 2, offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions, utranMobilityInformation_r3_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranMobilityInformation-r3-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_laterNonCriticalExtensions_oms_6[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_laterNonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_laterNonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utranMobilityInformation-r3-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_laterNonCriticalExtensions_specs_6 = {
	sizeof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions),
	offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions, _asn_ctx),
	asn_MAP_laterNonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_laterNonCriticalExtensions_oms_6,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laterNonCriticalExtensions_6 = {
	"laterNonCriticalExtensions",
	"laterNonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_laterNonCriticalExtensions_tags_6,
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_laterNonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_laterNonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_laterNonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v3a0NonCriticalExtensions_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions, utranMobilityInformation_v3a0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTRANMobilityInformation_v3a0ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranMobilityInformation-v3a0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions, laterNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_laterNonCriticalExtensions_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"laterNonCriticalExtensions"
		},
};
static const int asn_MAP_v3a0NonCriticalExtensions_oms_4[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v3a0NonCriticalExtensions_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v3a0NonCriticalExtensions_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utranMobilityInformation-v3a0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* laterNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v3a0NonCriticalExtensions_specs_4 = {
	sizeof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions),
	offsetof(struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v3a0NonCriticalExtensions_tag2el_4,
	2,	/* Count of tags in the map */
	asn_MAP_v3a0NonCriticalExtensions_oms_4,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v3a0NonCriticalExtensions_4 = {
	"v3a0NonCriticalExtensions",
	"v3a0NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v3a0NonCriticalExtensions_tags_4,
	sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_4[0]) - 1, /* 1 */
	asn_DEF_v3a0NonCriticalExtensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v3a0NonCriticalExtensions_4,
	2,	/* Elements count */
	&asn_SPC_v3a0NonCriticalExtensions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r3_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__r3, utranMobilityInformation_r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTRANMobilityInformation_r3_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranMobilityInformation-r3"
		},
	{ ATF_POINTER, 1, offsetof(struct UTRANMobilityInformation__r3, v3a0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v3a0NonCriticalExtensions_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v3a0NonCriticalExtensions"
		},
};
static const int asn_MAP_r3_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r3_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r3_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utranMobilityInformation-r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v3a0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r3_specs_2 = {
	sizeof(struct UTRANMobilityInformation__r3),
	offsetof(struct UTRANMobilityInformation__r3, _asn_ctx),
	asn_MAP_r3_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_r3_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r3_2 = {
	"r3",
	"r3",
	&asn_OP_SEQUENCE,
	asn_DEF_r3_tags_2,
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]) - 1, /* 1 */
	asn_DEF_r3_tags_2,	/* Same as above */
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r3_2,
	2,	/* Elements count */
	&asn_SPC_r3_specs_2	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_18 = {
	sizeof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_18 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_nonCriticalExtensions_tags_18,
	sizeof(asn_DEF_nonCriticalExtensions_tags_18)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_18[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_18,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_18)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_18[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions, utranMobilityInformation_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UtranMobilityInformation_v690ext_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranMobilityInformation-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_16[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utranMobilityInformation-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_16 = {
	sizeof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions),
	offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_16,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_16,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_16 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_v690NonCriticalExtensions_tags_16,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_16)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_16[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_16,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_16)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v690NonCriticalExtensions_16,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r5_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5, utranMobilityInformation_r5),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTRANMobilityInformation_r5_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utranMobilityInformation-r5"
		},
	{ ATF_POINTER, 1, offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_r5_oms_14[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r5_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r5_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utranMobilityInformation-r5 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r5_specs_14 = {
	sizeof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5),
	offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5, _asn_ctx),
	asn_MAP_r5_tag2el_14,
	2,	/* Count of tags in the map */
	asn_MAP_r5_oms_14,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r5_14 = {
	"r5",
	"r5",
	&asn_OP_SEQUENCE,
	asn_DEF_r5_tags_14,
	sizeof(asn_DEF_r5_tags_14)
		/sizeof(asn_DEF_r5_tags_14[0]) - 1, /* 1 */
	asn_DEF_r5_tags_14,	/* Same as above */
	sizeof(asn_DEF_r5_tags_14)
		/sizeof(asn_DEF_r5_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_r5_14,
	2,	/* Elements count */
	&asn_SPC_r5_specs_14	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_criticalExtensions_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensions_specs_19 = {
	sizeof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions),
	offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_19 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_criticalExtensions_tags_19,
	sizeof(asn_DEF_criticalExtensions_tags_19)
		/sizeof(asn_DEF_criticalExtensions_tags_19[0]) - 1, /* 1 */
	asn_DEF_criticalExtensions_tags_19,	/* Same as above */
	sizeof(asn_DEF_criticalExtensions_tags_19)
		/sizeof(asn_DEF_criticalExtensions_tags_19[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_criticalExtensions_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions, choice.r5),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r5_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_criticalExtensions_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r5 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_13 = {
	sizeof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions),
	offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions, _asn_ctx),
	offsetof(struct UTRANMobilityInformation__later_than_r3__criticalExtensions, present),
	sizeof(((struct UTRANMobilityInformation__later_than_r3__criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_13,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_13 = {
	"criticalExtensions",
	"criticalExtensions",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_criticalExtensions_constr_13, &asn_PER_type_criticalExtensions_constr_13, CHOICE_constraint },
	asn_MBR_criticalExtensions_13,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_later_than_r3_11[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__later_than_r3, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rrc-TransactionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation__later_than_r3, criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"criticalExtensions"
		},
};
static const ber_tlv_tag_t asn_DEF_later_than_r3_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_later_than_r3_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrc-TransactionIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_later_than_r3_specs_11 = {
	sizeof(struct UTRANMobilityInformation__later_than_r3),
	offsetof(struct UTRANMobilityInformation__later_than_r3, _asn_ctx),
	asn_MAP_later_than_r3_tag2el_11,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_later_than_r3_11 = {
	"later-than-r3",
	"later-than-r3",
	&asn_OP_SEQUENCE,
	asn_DEF_later_than_r3_tags_11,
	sizeof(asn_DEF_later_than_r3_tags_11)
		/sizeof(asn_DEF_later_than_r3_tags_11[0]) - 1, /* 1 */
	asn_DEF_later_than_r3_tags_11,	/* Same as above */
	sizeof(asn_DEF_later_than_r3_tags_11)
		/sizeof(asn_DEF_later_than_r3_tags_11[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_later_than_r3_11,
	2,	/* Elements count */
	&asn_SPC_later_than_r3_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UTRANMobilityInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation, choice.r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r3_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"r3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UTRANMobilityInformation, choice.later_than_r3),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_later_than_r3_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"later-than-r3"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UTRANMobilityInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* later-than-r3 */
};
asn_CHOICE_specifics_t asn_SPC_UTRANMobilityInformation_specs_1 = {
	sizeof(struct UTRANMobilityInformation),
	offsetof(struct UTRANMobilityInformation, _asn_ctx),
	offsetof(struct UTRANMobilityInformation, present),
	sizeof(((struct UTRANMobilityInformation *)0)->present),
	asn_MAP_UTRANMobilityInformation_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UTRANMobilityInformation = {
	"UTRANMobilityInformation",
	"UTRANMobilityInformation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_UTRANMobilityInformation_constr_1, &asn_PER_type_UTRANMobilityInformation_constr_1, CHOICE_constraint },
	asn_MBR_UTRANMobilityInformation_1,
	2,	/* Elements count */
	&asn_SPC_UTRANMobilityInformation_specs_1	/* Additional specs */
};

